"""
Django Admin configuration for the lead_engine app.

IMPORTANT DISTINCTION FROM THE TEACHER-FACING API: Django Admin is
a platform-operator tool, not the teacher-facing Lead Dashboard.
The masking rule in apps/lead_engine/serializers.py
(LeadSerializer/LeadListSerializer always hiding student contact
info from TEACHERS) does NOT apply here - an Admin/SuperAdmin
managing the platform legitimately needs to see real student
requirement and contact data to operate and moderate the system.
This distinction is intentional, not an inconsistency.
"""

from django.contrib import admin
from django.utils.translation import gettext_lazy as _

from apps.lead_engine.models import (
    Lead,
    LeadMatchScore,
    LeadUnlockHistory,
    LeadUnlockPricing,
)


@admin.register(Lead)
class LeadAdmin(admin.ModelAdmin):
    """
    Admin configuration for Lead records. Read-heavy by nature
    (leads are system-generated, not admin-authored), but status
    and contact_unlocked remain editable for manual
    operator intervention if ever needed (e.g. manually closing a
    stale lead).
    """

    list_display = (
        "get_subject",
        "get_student_name",
        "get_teacher_name",
        "status",
        "is_viewed",
        "contact_unlocked",
        "created_at",
    )
    list_filter = ("status", "is_viewed", "contact_unlocked", "is_deleted")
    search_fields = (
        "student_requirement__student__email",
        "student_requirement__student__first_name",
        "student_requirement__subject__name",
        "teacher_profile__teacher__user__email",
        "teacher_profile__teacher__user__first_name",
    )
    ordering = ("-created_at",)
    readonly_fields = (
        "id",
        "student_requirement",
        "teacher_profile",
        "created_at",
        "updated_at",
        "deleted_at",
        "viewed_at",
    )
    autocomplete_fields = ()  # student_requirement/teacher_profile are readonly, not editable

    fieldsets = (
        (None, {"fields": ("id", "student_requirement", "teacher_profile")}),
        (
            _("Status"),
            {"fields": ("status", "is_viewed", "viewed_at", "contact_unlocked")},
        ),
        (
            _("Soft Delete"),
            {"fields": ("is_deleted", "deleted_at"), "classes": ("collapse",)},
        ),
        (
            _("Timestamps"),
            {"fields": ("created_at", "updated_at"), "classes": ("collapse",)},
        ),
    )

    @admin.display(description=_("Subject"))
    def get_subject(self, obj):
        return obj.student_requirement.subject.name

    @admin.display(description=_("Student"))
    def get_student_name(self, obj):
        return obj.student_requirement.student.get_full_name()

    @admin.display(description=_("Teacher"))
    def get_teacher_name(self, obj):
        return obj.teacher_profile.teacher.user.get_full_name()

    def get_queryset(self, request):
        qs = self.model.all_objects.select_related(
            "student_requirement",
            "student_requirement__subject",
            "student_requirement__student",
            "teacher_profile",
            "teacher_profile__teacher",
            "teacher_profile__teacher__user",
        ).get_queryset()
        ordering = self.get_ordering(request)
        if ordering:
            qs = qs.order_by(*ordering)
        return qs

    def has_add_permission(self, request):
        """
        Leads are exclusively system-generated by the matching
        service (generate_leads_for_requirement) - disabling manual
        creation via Admin prevents operators from creating
        malformed/orphaned Lead records that bypass the matching
        logic entirely.
        """
        return False


@admin.register(LeadUnlockPricing)
class LeadUnlockPricingAdmin(admin.ModelAdmin):
    """
    Admin configuration for LeadUnlockPricing - where an operator
    configures the "Token Pricing" from the spec (School Tuition,
    Higher Secondary, Competitive Exams, Corporate Training).
    """

    list_display = ("get_tier_display", "token_cost", "is_active", "updated_at")
    list_filter = ("is_active",)
    ordering = ("tier",)
    readonly_fields = ("id", "created_at", "updated_at", "deleted_at")

    fieldsets = (
        (None, {"fields": ("id", "tier", "token_cost", "is_active")}),
        (
            _("Soft Delete"),
            {"fields": ("is_deleted", "deleted_at"), "classes": ("collapse",)},
        ),
        (
            _("Timestamps"),
            {"fields": ("created_at", "updated_at"), "classes": ("collapse",)},
        ),
    )

    @admin.display(description=_("Tier"), ordering="tier")
    def get_tier_display(self, obj):
        return obj.get_tier_display()

    def get_queryset(self, request):
        qs = self.model.all_objects.get_queryset()
        ordering = self.get_ordering(request)
        if ordering:
            qs = qs.order_by(*ordering)
        return qs


@admin.register(LeadUnlockHistory)
class LeadUnlockHistoryAdmin(admin.ModelAdmin):
    """
    Fully read-only, platform-wide admin for browsing every lead
    unlock event - the spec's "Lead Unlock History" admin panel
    requirement. Records are created exclusively by
    apps.lead_engine.unlock_service.unlock_lead_contact(), never
    manually.
    """

    list_display = (
        "get_teacher_name",
        "get_subject",
        "is_free_unlock",
        "tokens_deducted",
        "created_at",
    )
    list_filter = ("is_free_unlock", "created_at")
    search_fields = (
        "teacher__user__email",
        "teacher__user__first_name",
        "lead__student_requirement__subject__name",
    )
    ordering = ("-created_at",)
    readonly_fields = (
        "id",
        "teacher",
        "lead",
        "is_free_unlock",
        "tokens_deducted",
        "created_at",
        "updated_at",
        "deleted_at",
    )

    @admin.display(description=_("Teacher"), ordering="teacher__user__first_name")
    def get_teacher_name(self, obj):
        return obj.teacher.user.get_full_name()

    @admin.display(description=_("Subject"))
    def get_subject(self, obj):
        return obj.lead.student_requirement.subject.name

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False

    def get_queryset(self, request):
        qs = self.model.all_objects.select_related(
            "teacher",
            "teacher__user",
            "lead",
            "lead__student_requirement",
            "lead__student_requirement__subject",
        ).get_queryset()
        ordering = self.get_ordering(request)
        if ordering:
            qs = qs.order_by(*ordering)
        return qs


@admin.register(LeadMatchScore)
class LeadMatchScoreAdmin(admin.ModelAdmin):
    """
    Fully read-only admin for browsing every computed match score
    platform-wide - directly satisfies the spec's "Admin should be
    able to view: Matching Scores, Time Compatibility Scores, Lead
    Matching Results." Sortable/filterable by match_score and
    time_score specifically, since those are the two figures most
    useful for an admin auditing "is our matching engine working
    well."
    """

    list_display = (
        "get_teacher_name",
        "get_subject",
        "match_score",
        "time_score",
        "availability_status",
        "created_at",
    )
    list_filter = ("availability_status", "created_at")
    search_fields = (
        "lead__teacher_profile__teacher__user__email",
        "lead__student_requirement__subject__name",
    )
    ordering = ("-match_score",)
    readonly_fields = (
        "id",
        "lead",
        "match_score",
        "subject_score",
        "time_score",
        "language_score",
        "location_score",
        "budget_score",
        "rating_score",
        "experience_score",
        "verification_score",
        "response_rate_score",
        "premium_score",
        "best_matching_day",
        "best_matching_start_time",
        "best_matching_end_time",
        "best_matching_timezone",
        "availability_status",
        "created_at",
        "updated_at",
        "deleted_at",
    )

    fieldsets = (
        (None, {"fields": ("id", "lead", "match_score", "availability_status")}),
        (
            _("Score Breakdown"),
            {
                "fields": (
                    "subject_score",
                    "time_score",
                    "language_score",
                    "location_score",
                    "budget_score",
                    "rating_score",
                    "experience_score",
                    "verification_score",
                    "response_rate_score",
                    "premium_score",
                )
            },
        ),
        (
            _("Best Matching Slot"),
            {
                "fields": (
                    "best_matching_day",
                    "best_matching_start_time",
                    "best_matching_end_time",
                    "best_matching_timezone",
                )
            },
        ),
        (
            _("Timestamps"),
            {"fields": ("created_at", "updated_at"), "classes": ("collapse",)},
        ),
    )

    @admin.display(description=_("Teacher"))
    def get_teacher_name(self, obj):
        return obj.lead.teacher_profile.teacher.user.get_full_name()

    @admin.display(description=_("Subject"))
    def get_subject(self, obj):
        return obj.lead.student_requirement.subject.name

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False

    def get_queryset(self, request):
        qs = self.model.all_objects.select_related(
            "lead",
            "lead__teacher_profile",
            "lead__teacher_profile__teacher",
            "lead__teacher_profile__teacher__user",
            "lead__student_requirement",
            "lead__student_requirement__subject",
        ).get_queryset()
        ordering = self.get_ordering(request)
        if ordering:
            qs = qs.order_by(*ordering)
        return qs
