"""
Lead model for the Teacher Marketplace Platform.

A Lead links one StudentRequirement to one matching TeacherProfile.
Leads are generated automatically by the matching service
(apps/lead_engine/services.py, next file) when a student submits a
requirement - they are never created directly by a client via the
API.

CRITICAL Phase 2 boundary: contact_unlocked is ALWAYS False in this
phase. There is no code path anywhere in Phase 2 that sets it to
True - that logic (token deduction, unlock action) is explicitly
Phase 3 scope (Wallet, Coin Deduction, Lead Unlocking). The field
exists now so the schema doesn't need to change when Phase 3 adds
the unlock mechanism, but no unlock functionality is implemented
here.
"""

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.common.models import BaseModel
from apps.student_requirement.models import StudentRequirement
from apps.teacher_profile.models import TeacherProfile


class LeadStatus(models.TextChoices):
    """
    Lifecycle status of a Lead from the teacher's perspective.
        NEW      - generated by the matching service, not yet
                   viewed by the teacher
        VIEWED   - the teacher has opened/viewed this lead's details
        CLOSED   - no longer relevant (e.g. the underlying
                   StudentRequirement was closed/withdrawn)
    """

    NEW = "new", _("New")
    VIEWED = "viewed", _("Viewed")
    CLOSED = "closed", _("Closed")


class Lead(BaseModel):
    """
    Links a StudentRequirement to a matching TeacherProfile.
    Inherits from BaseModel: UUID PK, created_at/updated_at
    (satisfies "Lead Created Time"), soft-delete, and audit fields
    are already provided.
    """

    student_requirement = models.ForeignKey(
        StudentRequirement,
        related_name="leads",
        on_delete=models.CASCADE,
        help_text=_("The student requirement this lead was generated from."),
    )
    teacher_profile = models.ForeignKey(
        TeacherProfile,
        related_name="leads",
        on_delete=models.CASCADE,
        help_text=_("The teacher profile matched to this requirement."),
    )
    status = models.CharField(
        _("status"),
        max_length=10,
        choices=LeadStatus.choices,
        default=LeadStatus.NEW,
        db_index=True,
    )
    is_viewed = models.BooleanField(
        _("is viewed"),
        default=False,
        help_text=_(
            "Whether the teacher has opened this lead's details at least once."
        ),
    )
    viewed_at = models.DateTimeField(
        _("viewed at"),
        null=True,
        blank=True,
    )
    contact_unlocked = models.BooleanField(
        _("contact unlocked"),
        default=False,
        help_text=_(
            "Always False in Phase 2. Unlocking (via token deduction) is "
            "implemented in Phase 3 - this field exists now purely so "
            "the schema is stable ahead of that phase."
        ),
    )

    class Meta:
        verbose_name = _("Lead")
        verbose_name_plural = _("Leads")
        ordering = ["-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["student_requirement", "teacher_profile"],
                name="unique_lead_per_requirement_teacher_pair",
            ),
        ]
        indexes = [
            models.Index(fields=["teacher_profile", "status"]),
            models.Index(fields=["student_requirement", "status"]),
        ]

    def __str__(self):
        return (
            f"Lead: {self.student_requirement.subject.name} -> "
            f"{self.teacher_profile.teacher.user.get_full_name()}"
        )

    def mark_viewed(self):
        """
        Marks this lead as viewed, setting both is_viewed and
        viewed_at, and advancing status from NEW to VIEWED (but
        never downgrading from a later status like CLOSED). Called
        by the lead detail view when a teacher opens a lead.
        """
        from django.utils import timezone

        if not self.is_viewed:
            self.is_viewed = True
            self.viewed_at = timezone.now()
            if self.status == LeadStatus.NEW:
                self.status = LeadStatus.VIEWED
            self.save(update_fields=["is_viewed", "viewed_at", "status"])


class PricingTier(models.TextChoices):
    """
    Matches the spec's exact example tiers: School Tuition, Higher
    Secondary, Competitive Exams, Corporate Training. Kept as a
    small fixed enum (not a free-text field or a link to Subject)
    since these are broad pricing CATEGORIES, not tied 1:1 to any
    single Subject - many subjects could fall under "School
    Tuition" pricing, for instance.
    """

    SCHOOL_TUITION = "school_tuition", _("School Tuition")
    HIGHER_SECONDARY = "higher_secondary", _("Higher Secondary")
    COMPETITIVE_EXAMS = "competitive_exams", _("Competitive Exams")
    CORPORATE_TRAINING = "corporate_training", _("Corporate Training")


class LeadUnlockPricing(BaseModel):
    """
    Admin-configurable token cost to unlock a lead, per pricing
    tier. Satisfies the spec's "Token Pricing" section: "Create
    configurable pricing... Admin should configure this."

    One active row per tier is expected (enforced via unique=True
    on tier, not a composite constraint, since tier alone should
    be unique - there's no second dimension to key on).
    """

    tier = models.CharField(
        _("pricing tier"),
        max_length=20,
        choices=PricingTier.choices,
        unique=True,
        db_index=True,
    )
    token_cost = models.PositiveIntegerField(
        _("token cost"),
        validators=[MinValueValidator(1), MaxValueValidator(100_000)],
        help_text=_("Number of tokens required to unlock a lead in this tier."),
    )
    is_active = models.BooleanField(_("is active"), default=True, db_index=True)

    class Meta:
        verbose_name = _("Lead Unlock Pricing")
        verbose_name_plural = _("Lead Unlock Pricing")
        ordering = ["tier"]
        constraints = [
            models.CheckConstraint(
                name="lead_unlock_pricing_token_cost_range",
                check=models.Q(token_cost__gte=1) & models.Q(token_cost__lte=100_000),
            ),
        ]

    def __str__(self):
        return f"{self.get_tier_display()}: {self.token_cost} tokens"


class LeadUnlockHistory(BaseModel):
    """
    Immutable audit record of a single lead unlock event - free or
    paid. Satisfies the spec's "Lead Unlock History" section
    exactly: Teacher, Lead, Unlock Time (created_at, inherited),
    Free Unlock, Paid Unlock, Tokens Deducted.

    Created exclusively by apps.lead_engine.unlock_service - never
    directly via a client-facing write endpoint.
    """

    teacher = models.ForeignKey(
        "teachers.Teacher",
        related_name="lead_unlock_history",
        on_delete=models.CASCADE,
    )
    lead = models.ForeignKey(
        Lead,
        related_name="unlock_history",
        on_delete=models.CASCADE,
    )
    is_free_unlock = models.BooleanField(
        _("free unlock"),
        help_text=_(
            "True if this unlock consumed a free monthly lead; False if it consumed tokens."
        ),
    )
    tokens_deducted = models.PositiveIntegerField(
        _("tokens deducted"),
        default=0,
        help_text=_("0 for a free unlock; the token cost charged for a paid unlock."),
    )

    class Meta:
        verbose_name = _("Lead Unlock History")
        verbose_name_plural = _("Lead Unlock History")
        ordering = ["-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["teacher", "lead"],
                name="unique_unlock_per_teacher_per_lead",
            ),
        ]
        indexes = [
            models.Index(fields=["teacher", "is_free_unlock"]),
        ]

    def __str__(self):
        kind = (
            "Free" if self.is_free_unlock else f"Paid ({self.tokens_deducted} tokens)"
        )
        return f"{self.teacher.user.get_full_name()} unlocked {self.lead} - {kind}"


class LeadMatchScore(BaseModel):
    """
    Persists the full matching score breakdown for a single Lead,
    computed once at lead-generation time by
    apps.lead_engine.services.matching_service.MatchingService (see
    that file). One-to-one with Lead - every Lead created by the
    new matching-aware generation flow has exactly one
    LeadMatchScore row.

    Field names deliberately mirror the spec's exact API response
    shape (match_score, subject_score, time_score, etc.) so the
    serializer for GET /api/v1/leads/{id}/matches/ can be a nearly
    direct pass-through of this model, rather than reshaping data
    at the API layer.

    All *_score fields are stored as 0-100 integers (percentages),
    not 0.0-1.0 floats, matching the spec's own example response
    ("match_score": 91) - the MatchingService computes in 0.0-1.0
    internally for weight-multiplication convenience, then scales
    to 0-100 only at the point of persisting here.
    """

    lead = models.OneToOneField(
        "Lead",
        related_name="match_score",
        on_delete=models.CASCADE,
    )

    match_score = models.PositiveSmallIntegerField(
        _("match score"),
        validators=[MaxValueValidator(100)],
        db_index=True,
        help_text=_(
            "Composite weighted score, 0-100. See settings.MATCHING_WEIGHTS for component weights."
        ),
    )
    subject_score = models.PositiveSmallIntegerField(
        _("subject score"), validators=[MaxValueValidator(100)]
    )
    time_score = models.PositiveSmallIntegerField(
        _("time score"),
        validators=[MaxValueValidator(100)],
        db_index=True,
        help_text=_(
            "Time compatibility score, 0-100 - see TimeCompatibilityService for the overlap calculation."
        ),
    )
    language_score = models.PositiveSmallIntegerField(
        _("language score"), validators=[MaxValueValidator(100)]
    )
    location_score = models.PositiveSmallIntegerField(
        _("location score"), validators=[MaxValueValidator(100)]
    )
    budget_score = models.PositiveSmallIntegerField(
        _("budget score"), validators=[MaxValueValidator(100)]
    )
    rating_score = models.PositiveSmallIntegerField(
        _("rating score"), validators=[MaxValueValidator(100)]
    )
    experience_score = models.PositiveSmallIntegerField(
        _("experience score"), validators=[MaxValueValidator(100)]
    )
    verification_score = models.PositiveSmallIntegerField(
        _("verification score"), validators=[MaxValueValidator(100)]
    )
    response_rate_score = models.PositiveSmallIntegerField(
        _("response rate score"),
        validators=[MaxValueValidator(100)],
        default=100,
        help_text=_(
            "Always 100 in this implementation - no teacher response-time "
            "tracking exists yet anywhere in this codebase. Stored now so "
            "the field/weight exists and a future phase can populate it "
            "with real data without a schema change. See matching_service.py."
        ),
    )
    premium_score = models.PositiveSmallIntegerField(
        _("premium score"), validators=[MaxValueValidator(100)]
    )

    best_matching_day = models.PositiveSmallIntegerField(
        _("best matching day"),
        null=True,
        blank=True,
        help_text=_(
            "DayOfWeek value (1=Monday...7=Sunday) of the best overlapping slot found, if any."
        ),
    )
    best_matching_start_time = models.TimeField(
        _("best matching start time"), null=True, blank=True
    )
    best_matching_end_time = models.TimeField(
        _("best matching end time"), null=True, blank=True
    )
    best_matching_timezone = models.CharField(
        _("best matching timezone"),
        max_length=64,
        null=True,
        blank=True,
        help_text=_(
            "Timezone the best_matching_* times are expressed in (the student's preference timezone)."
        ),
    )

    class AvailabilityStatus(models.TextChoices):
        COMPATIBLE = "compatible", _("Compatible")
        PARTIALLY_COMPATIBLE = "partially_compatible", _("Partially Compatible")
        INCOMPATIBLE = "incompatible", _("Incompatible")

    availability_status = models.CharField(
        _("availability status"),
        max_length=25,
        choices=AvailabilityStatus.choices,
        db_index=True,
    )

    class Meta:
        verbose_name = _("Lead Match Score")
        verbose_name_plural = _("Lead Match Scores")
        ordering = ["-match_score"]
        indexes = [
            # Supports RankingService's core query: "given a set of
            # leads for a requirement, order by match_score desc" -
            # and Admin's "view Matching Scores" browsing/sorting.
            models.Index(fields=["match_score"], name="idx_match_score"),
            models.Index(
                fields=["availability_status"], name="idx_availability_status"
            ),
        ]

    def __str__(self):
        return f"{self.lead} - {self.match_score}% match"
