# Generated by Django 5.0.6 on 2026-08-06 11:20

import apps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=150,
                validators=[apps.utils.validators.validate_name],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=150,
                validators=[apps.utils.validators.validate_name],
                verbose_name="last name",
            ),
        ),
    ]
