# Generated by Django 5.0.14 on 2026-09-18 08:23

import apps.utils.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminloginrequest_impersonationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_account_name',
            field=models.CharField(blank=True, db_index=True, help_text="Login identifier for role=admin accounts created via the self-service admin-account-request flow, e.g. 'RajuDas@Finance'. Null for every other role, and for admin accounts that predate this flow (they keep signing in the old, email-based way).", max_length=190, null=True, unique=True, verbose_name='admin account name'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_seen_admin_credentials_notice',
            field=models.BooleanField(default=False, help_text='Flips to True the first time this admin successfully signs in via the admin login page - after that, the one-time account-name-and-password reveal is never shown again.', verbose_name='has seen admin credentials notice'),
        ),
        migrations.CreateModel(
            name='AdminDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted, if applicable.', null=True)),
                ('name', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin department',
                'verbose_name_plural': 'Admin departments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='admin_department',
            field=models.ForeignKey(blank=True, help_text='Department this admin was assigned when approved. Null for non-admins.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admins', to='accounts.admindepartment', verbose_name='admin department'),
        ),
        migrations.CreateModel(
            name='AdminAccountRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted, if applicable.', null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email address')),
                ('mobile', models.CharField(max_length=17, validators=[apps.utils.validators.validate_mobile_number], verbose_name='mobile number')),
                ('first_name', models.CharField(max_length=150, validators=[apps.utils.validators.validate_name], verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, validators=[apps.utils.validators.validate_name], verbose_name='last name')),
                ('password_hash', models.CharField(max_length=255, verbose_name='password hash')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=10, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('deny_reason', models.CharField(blank=True, max_length=500, verbose_name='deny reason')),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='requested ip')),
                ('requested_user_agent', models.CharField(blank=True, max_length=400, verbose_name='requested user agent')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('created_user', models.OneToOneField(blank=True, help_text='The User row created on approval. Null while pending/denied.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_account_request', to=settings.AUTH_USER_MODEL, verbose_name='created user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_account_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Set only at approval time, together with status=approved.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_requests', to='accounts.admindepartment', verbose_name='department')),
            ],
            options={
                'verbose_name': 'Admin account request',
                'verbose_name_plural': 'Admin account requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='accounts_ad_status_845480_idx')],
            },
        ),
    ]
