# Generated by Django 5.0.14 on 2026-09-21 11:14

import apps.utils.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_admin_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccountrequest',
            name='organization_name',
            field=models.CharField(blank=True, default='', help_text="Set only for a Learning Partner request (blank for a normal admin request). Becomes the created admin's display name and the basis of their generated account name, e.g. 'Learn Academy' -> 'LearnAcademy@LearningPartner'.", max_length=190, validators=[apps.utils.validators.validate_taxonomy_name], verbose_name='organisation name'),
        ),
        migrations.AddField(
            model_name='admindepartment',
            name='is_learning_partner',
            field=models.BooleanField(db_index=True, default=False, help_text="True for exactly one seeded department ('Learning Partner'). Admins in this department each represent one partner organisation (school/coaching centre) rather than an internal staff member - never settable via the API.", verbose_name='is learning partner'),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_partner',
            field=models.ForeignKey(blank=True, help_text='The Learning Partner organisation (an admin User whose department is the Learning Partner department) this student/teacher identified at signup. Null for everyone else.', limit_choices_to={'admin_department__is_learning_partner': True, 'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL, verbose_name='learning partner'),
        ),
        migrations.AlterField(
            model_name='adminaccountrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[apps.utils.validators.validate_name], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='adminaccountrequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[apps.utils.validators.validate_name], verbose_name='last name'),
        ),
    ]
