# Generated by Django 5.0.14 on 2026-09-22 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_seed_learning_partner_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminaccountrequest",
            name="requested_department",
            field=models.ForeignKey(
                blank=True,
                help_text="The department the requester asked to join at submission time (mandatory on the public request form; auto-set to Learning Partner for a Learning Partner request). Distinct from `department`, which is set at approval and may point elsewhere if a Super Admin assigns a different department.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_account_requests",
                to="accounts.admindepartment",
                verbose_name="requested department",
            ),
        ),
    ]
