# Generated by Django 5.0.14 on 2026-09-23 06:12, hand-split (see 0011/0012):
# adds the LEARNING_PARTNER role choice + repoints limit_choices_to first, so
# the 0011 data migration below can move existing LP admins onto the new
# role while AdminDepartment.is_learning_partner still exists to read from.
# 0012 removes that now-unused field afterwards.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_adminaccountrequest_requested_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="learning_partner",
            field=models.ForeignKey(
                blank=True,
                help_text="The Learning Partner organisation (a User with role=learning_partner) this student/teacher identified at signup. Null for everyone else.",
                limit_choices_to={"role": "learning_partner"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="learning partner",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                    ("superadmin", "Super Admin"),
                    ("learning_partner", "Learning Partner"),
                ],
                db_index=True,
                default="student",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
