# Generated by Django 5.0.6 on 2026-09-01 07:56

import apps.utils.validators
import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_seed_default_plans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="bonus_tokens",
            field=models.PositiveIntegerField(
                default=0,
                help_text="One-time bonus tokens credited to the wallet when a teacher subscribes to this plan.",
                validators=[django.core.validators.MaxValueValidator(1000000)],
                verbose_name="bonus tokens on subscribe",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="free_leads",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of leads this plan lets a teacher unlock for free each month.",
                validators=[django.core.validators.MaxValueValidator(100000)],
                verbose_name="free leads per month",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="lead_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Multiplier applied to how many leads this teacher is matched with, relative to baseline (e.g. 1.5 = 50% more lead visibility). Phase 3 note: stored as configurable plan data; actual application inside lead_engine's matching algorithm is intentionally out of scope for Phase 3's synchronous, simple matching pass - flagged here rather than silently implemented as a hidden behavior change to Phase 2's engine.",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("10.00")),
                ],
                verbose_name="lead multiplier",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="monthly_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1000000.00")),
                ],
                verbose_name="monthly price",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                help_text="e.g. 'Free', 'Professional', 'Elite'.",
                max_length=100,
                unique=True,
                validators=[apps.utils.validators.validate_taxonomy_name],
                verbose_name="plan name",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="priority_rank",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Higher rank = higher priority in search/listing ordering. Phase 3 note: this field is stored and available for apps.search to consume as a ranking signal, but wiring it into search's actual ordering logic is left as a follow-up - see the note in this app's admin.py.",
                validators=[django.core.validators.MaxValueValidator(1000)],
                verbose_name="priority rank",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.CheckConstraint(
                check=models.Q(("name__regex", "^\\s*$"), _negated=True),
                name="subscription_plan_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("monthly_price__gte", Decimal("0.00")),
                    ("monthly_price__lte", Decimal("1000000.00")),
                    ("free_leads__lte", 100000),
                    ("priority_rank__lte", 1000),
                    ("lead_multiplier__gte", Decimal("0.00")),
                    ("lead_multiplier__lte", Decimal("10.00")),
                    ("bonus_tokens__lte", 1000000),
                ),
                name="subscription_plan_sane_ranges",
            ),
        ),
    ]
