# Generated by Django 5.0.14 on 2026-09-09 06:18

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscriptionplan_bonus_tokens_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="compare_at_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional 'was' price shown struck through next to monthly_price to advertise a discount (e.g. compare_at_price=199.00 with monthly_price=99.00 displays '₹199 → ₹99, 50% off'). Null when this plan isn't being shown as discounted.",
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1000000.00")),
                ],
                verbose_name="compare-at price",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("compare_at_price__isnull", True),
                    ("compare_at_price__gt", models.F("monthly_price")),
                    _connector="OR",
                ),
                name="subscription_plan_compare_at_price_is_a_real_discount",
            ),
        ),
    ]
