# Generated by Django 5.0.6 on 2026-08-12 11:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current token balance. NEVER set this directly - always go through WalletService.credit()/debit()/refund().",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="balance",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.OneToOneField(
                        help_text="The Teacher who owns this wallet. Students never have a wallet.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                            ("refund", "Refund"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="transaction type",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Number of tokens involved in this transaction (always positive).",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="amount",
                    ),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(
                        help_text="The wallet's balance immediately after this transaction was applied.",
                        verbose_name="balance after",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="success",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="External or internal reference this transaction relates to, e.g. a Payment id, a Lead id (unlock debit), or a refund reason code. Not a foreign key since the reference type varies by transaction_type.",
                        max_length=255,
                        null=True,
                        verbose_name="reference id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Human-readable summary, e.g. 'Token package purchase - Professional'.",
                        max_length=255,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Transaction",
                "verbose_name_plural": "Wallet Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "transaction_type"],
                        name="wallet_wall_wallet__4de8fb_idx",
                    ),
                    models.Index(
                        fields=["wallet", "created_at"],
                        name="wallet_wall_wallet__83a8d3_idx",
                    ),
                    models.Index(
                        fields=["reference_id"], name="wallet_wall_referen_36d9a9_idx"
                    ),
                ],
            },
        ),
    ]
