# Generated by Django 5.0.6 on 2026-09-01 07:37

import apps.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional short description of what this subject covers.",
                max_length=1000,
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon identifier for frontend display (e.g. an icon library class name or a media path). Not a file upload in Phase 2 - kept as a simple string reference.",
                max_length=100,
                null=True,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="icon",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Display name of the subject, e.g. 'Mathematics'.",
                max_length=150,
                unique=True,
                validators=[apps.utils.validators.validate_taxonomy_name],
                verbose_name="name",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.CheckConstraint(
                check=models.Q(("name__regex", "^\\s*$"), _negated=True),
                name="subject_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("description__isnull", True),
                        models.Q(("description__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("icon__isnull", True),
                        models.Q(("icon__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                ),
                name="subject_text_fields_not_blank",
            ),
        ),
    ]
