# Generated by Django 5.0.14 on 2026-09-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_description_alter_subject_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_skill_based',
            field=models.BooleanField(db_index=True, default=False, help_text="True for subjects learned as a skill rather than an academic grade (e.g. Music, an instrument, Karate) - the sign-up 'What level?' step offers Novice/Intermediate/Expert for these instead of the Class 1-5 / Undergraduate / ... academic bands, which don't make sense for e.g. a 40-year-old learning guitar.", verbose_name='is skill based'),
        ),
    ]
