# Generated by Django 5.0.14 on 2026-09-21 13:44

import apps.utils.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_seed_skill_based_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='learning_partner',
            field=models.ForeignKey(blank=True, help_text="Null = platform-wide, visible to everyone. Set = a Learning Partner-requested subject, visible only to that partner's own students/teachers.", limit_choices_to={'admin_department__is_learning_partner': True, 'role': 'admin'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoped_subjects', to=settings.AUTH_USER_MODEL, verbose_name='learning partner'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_index=True, help_text="Display name of the subject, e.g. 'Mathematics'.", max_length=150, validators=[apps.utils.validators.validate_taxonomy_name], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier, auto-generated from name if left blank.', max_length=170, verbose_name='slug'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('learning_partner__isnull', True)), fields=('name',), name='subject_name_unique_global'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('learning_partner__isnull', True)), fields=('slug',), name='subject_slug_unique_global'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name', 'learning_partner'), name='subject_name_unique_per_partner'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('slug', 'learning_partner'), name='subject_slug_unique_per_partner'),
        ),
    ]
