# Generated by Django 5.0.6 on 2026-09-01 06:36

import apps.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="bio",
            field=models.CharField(
                blank=True,
                help_text="Short description of what the student is looking for.",
                max_length=1000,
                null=True,
                verbose_name="bio",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[apps.utils.validators.validate_place_name],
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="country",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[apps.utils.validators.validate_place_name],
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade_or_year",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'Grade 10', '2nd Year B.Sc', 'UPSC Aspirant'.",
                max_length=50,
                null=True,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="grade / year",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="preferred_subjects",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of subjects the student is looking for help with.",
                max_length=500,
                null=True,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="preferred subjects",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="state",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[apps.utils.validators.validate_place_name],
                verbose_name="state",
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("grade_or_year__isnull", True),
                        models.Q(("grade_or_year__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("city__isnull", True),
                        models.Q(("city__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("state__isnull", True),
                        models.Q(("state__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("country__isnull", True),
                        models.Q(("country__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("bio__isnull", True),
                        models.Q(("bio__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                ),
                name="student_text_fields_not_blank",
            ),
        ),
    ]
