# Generated by Django 5.0.6 on 2026-09-01 12:01

import apps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_bio_alter_student_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="students/profile_photos/%Y/%m/",
                validators=[apps.utils.validators.validate_image_upload],
                verbose_name="profile photo",
            ),
        ),
    ]
