# Generated by Django 5.0.6 on 2026-08-11 07:25

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages", "0001_initial"),
        ("location", "0001_initial"),
        ("subjects", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text="Short tagline, e.g. 'Experienced Mathematics Tutor for Grades 6-12'.",
                        max_length=200,
                        null=True,
                        verbose_name="headline",
                    ),
                ),
                (
                    "teaching_mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("both", "Both"),
                        ],
                        db_index=True,
                        default="both",
                        max_length=10,
                        verbose_name="teaching mode",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hourly rate in the platform's base currency.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="hourly rate",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average rating out of 5.00. Phase 2 note: this field exists for search/display/sorting purposes, but no review/rating submission system is built in this phase - it is manually adjustable (e.g. via Admin) until a later phase introduces actual student reviews.",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                        verbose_name="rating",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="verification status",
                    ),
                ),
                (
                    "cities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Cities this teacher offers offline/in-person teaching in. Not required for teachers who are Online-only.",
                        related_name="teacher_profiles",
                        to="location.city",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Languages this teacher can teach in.",
                        related_name="teacher_profiles",
                        to="languages.language",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Subjects this teacher can teach.",
                        related_name="teacher_profiles",
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.OneToOneField(
                        help_text="The Phase 1 Teacher record this professional profile extends.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_profile",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Profile",
                "verbose_name_plural": "Teacher Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "day_type",
                    models.CharField(
                        choices=[("weekdays", "Weekdays"), ("weekends", "Weekends")],
                        max_length=10,
                        verbose_name="day type",
                    ),
                ),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                        ],
                        max_length=10,
                        verbose_name="time slot",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="teacher_profile.teacherprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Availability",
                "verbose_name_plural": "Teacher Availability Slots",
                "ordering": ["day_type", "time_slot"],
            },
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["teaching_mode", "verification_status"],
                name="teacher_pro_teachin_24ef40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["hourly_rate"], name="teacher_pro_hourly__223227_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(fields=["rating"], name="teacher_pro_rating_f4baa6_idx"),
        ),
        migrations.AddConstraint(
            model_name="teacheravailability",
            constraint=models.UniqueConstraint(
                fields=("teacher_profile", "day_type", "time_slot"),
                name="unique_availability_slot_per_teacher",
            ),
        ),
    ]
