# Generated by Django 5.0.6 on 2026-08-13 12:11

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_profile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherScheduleException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("holiday", "Holiday"),
                            ("temporary_unavailable", "Temporary Unavailability"),
                            ("schedule_change", "One-time Schedule Change"),
                        ],
                        default="temporary_unavailable",
                        max_length=25,
                        verbose_name="exception type",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="The specific calendar date this exception applies to.",
                        verbose_name="date",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Leave blank (with end_time also blank) to mark the ENTIRE day unavailable.",
                        null=True,
                        verbose_name="start time",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="end time"),
                ),
                (
                    "timezone",
                    models.CharField(
                        help_text="IANA timezone name for start_time/end_time, if set.",
                        max_length=64,
                        verbose_name="timezone",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="reason"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="teacher_profile.teacherprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Schedule Exception",
                "verbose_name_plural": "Teacher Schedule Exceptions",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["teacher_profile", "date"],
                        name="idx_teacher_exception_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TeacherWeeklyAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        db_index=True,
                        verbose_name="day of week",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Local start time in this row's timezone, e.g. 18:00.",
                        verbose_name="start time",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="Local end time in this row's timezone, e.g. 20:00.",
                        verbose_name="end time",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        help_text="IANA timezone name, e.g. 'Asia/Kolkata', 'America/New_York'.",
                        max_length=64,
                        verbose_name="timezone",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive windows are excluded from matching without deleting the row.",
                        verbose_name="is active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_availability",
                        to="teacher_profile.teacherprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Weekly Availability",
                "verbose_name_plural": "Teacher Weekly Availability Windows",
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["teacher_profile", "day_of_week", "is_active"],
                        name="idx_teacher_avail_lookup",
                    ),
                    models.Index(
                        fields=["day_of_week", "is_active"],
                        name="idx_avail_day_analytics",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="teacherweeklyavailability",
            constraint=models.UniqueConstraint(
                fields=(
                    "teacher_profile",
                    "day_of_week",
                    "start_time",
                    "end_time",
                    "timezone",
                ),
                name="unique_teacher_availability_window",
            ),
        ),
    ]
