# Generated by Django 5.0.6 on 2026-09-01 06:56

from decimal import Decimal

import django.core.validators
from django.conf import settings
from django.db import migrations, models

import apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
        ("location", "0001_initial"),
        ("subjects", "0001_initial"),
        (
            "teacher_profile",
            "0002_teacherscheduleexception_teacherweeklyavailability_and_more",
        ),
        ("teachers", "0003_alter_teacher_bio_alter_teacher_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofile",
            name="headline",
            field=models.CharField(
                blank=True,
                help_text="Short tagline, e.g. 'Experienced Mathematics Tutor for Grades 6-12'.",
                max_length=200,
                null=True,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="headline",
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hourly rate in the platform's base currency.",
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1000000.00")),
                ],
                verbose_name="hourly rate",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherprofile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("headline__isnull", True),
                    models.Q(("headline__regex", "^\\s*$"), _negated=True),
                    _connector="OR",
                ),
                name="teacher_profile_headline_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherprofile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("hourly_rate__isnull", True),
                    models.Q(
                        ("hourly_rate__gte", Decimal("0.00")),
                        ("hourly_rate__lte", Decimal("1000000.00")),
                    ),
                    _connector="OR",
                ),
                name="teacher_profile_hourly_rate_range",
            ),
        ),
    ]
