# Generated by Django 5.0.6 on 2026-09-01 06:57

from django.conf import settings
from django.db import migrations, models

import apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_profile", "0003_alter_teacherprofile_headline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherscheduleexception",
            name="reason",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherscheduleexception",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("reason__isnull", True),
                    models.Q(("reason__regex", "^\\s*$"), _negated=True),
                    _connector="OR",
                ),
                name="teacher_exception_reason_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherscheduleexception",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("start_time__isnull", True), ("end_time__isnull", True)),
                    models.Q(
                        ("start_time__isnull", False), ("end_time__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="teacher_exception_time_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherscheduleexception",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("start_time__isnull", True),
                    ("start_time__lt", models.F("end_time")),
                    _connector="OR",
                ),
                name="teacher_exception_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherweeklyavailability",
            constraint=models.CheckConstraint(
                check=models.Q(("start_time__lt", models.F("end_time"))),
                name="teacher_avail_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherweeklyavailability",
            constraint=models.CheckConstraint(
                check=models.Q(("timezone__regex", "^\\s*$"), _negated=True),
                name="teacher_avail_timezone_not_blank",
            ),
        ),
    ]
