# Generated by Django 5.0.14 on 2026-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_profile", "0004_alter_teacherscheduleexception_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="moderation_status",
            field=models.CharField(
                choices=[("clear", "Clear"), ("held", "Held for review")],
                db_index=True,
                default="clear",
                help_text="HELD = flagged for off-platform contact/payment content; hidden from search + lead distribution (Phase 8b), still visible to the teacher.",
                max_length=8,
                verbose_name="moderation status",
            ),
        ),
    ]
