# Generated by Django 5.0.14 on 2026-09-13 12:15

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_code_alter_language_name_and_more'),
        ('location', '0002_alter_city_name_alter_country_code_and_more'),
        ('subjects', '0004_seed_skill_based_subjects'),
        ('teacher_profile', '0005_teacherprofile_moderation_status'),
        ('teachers', '0004_alter_teacher_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Monthly rate in the platform's base currency. Optional - a teacher may share this, an hourly_rate, both, or neither.", max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10000000.00'))], verbose_name='monthly rate'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Hourly rate in the platform's base currency. Optional - a teacher may share this, a monthly_rate, both, or neither.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000000.00'))], verbose_name='hourly rate'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.CheckConstraint(check=models.Q(('monthly_rate__isnull', True), models.Q(('monthly_rate__gte', Decimal('0.00')), ('monthly_rate__lte', Decimal('10000000.00'))), _connector='OR'), name='teacher_profile_monthly_rate_range'),
        ),
    ]
