# Generated by Django 5.0.14 on 2026-09-14 09:00

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_code_alter_language_name_and_more'),
        ('location', '0002_alter_city_name_alter_country_code_and_more'),
        ('subjects', '0004_seed_skill_based_subjects'),
        ('teacher_profile', '0006_teacherprofile_monthly_rate_and_more'),
        ('teachers', '0004_alter_teacher_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='monthly_rate_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The high end of the monthly rate range. Meaningless without monthly_rate also set - see that field's help text.", max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10000000.00'))], verbose_name='monthly rate (up to)'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Monthly rate in the platform's base currency - the low end of the range when monthly_rate_max is also set (fees genuinely vary by class size/level for most teachers), or a single fixed price when monthly_rate_max is left blank. Optional - a teacher may share this, an hourly_rate, both, or neither.", max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10000000.00'))], verbose_name='monthly rate'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.CheckConstraint(check=models.Q(('monthly_rate_max__isnull', True), models.Q(('monthly_rate_max__gte', Decimal('0.00')), ('monthly_rate_max__lte', Decimal('10000000.00'))), _connector='OR'), name='teacher_profile_monthly_rate_max_range'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.CheckConstraint(check=models.Q(('monthly_rate_max__isnull', True), ('monthly_rate__isnull', True), ('monthly_rate_max__gte', models.F('monthly_rate')), _connector='OR'), name='teacher_profile_monthly_rate_max_gte_min'),
        ),
    ]
