# Generated by Django 5.0.6 on 2026-08-12 11:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWebhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Razorpay event name, e.g. 'payment.captured', 'payment.failed'.",
                        max_length=100,
                        verbose_name="event type",
                    ),
                ),
                (
                    "razorpay_event_id",
                    models.CharField(
                        db_index=True,
                        help_text="Used to detect and ignore duplicate webhook deliveries (Razorpay may retry).",
                        max_length=100,
                        unique=True,
                        verbose_name="Razorpay event id",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="The full raw webhook payload as received, for audit/debugging.",
                        verbose_name="payload",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is processed"
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        help_text="Populated if processing this webhook raised an error, for debugging.",
                        null=True,
                        verbose_name="processing error",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Webhook",
                "verbose_name_plural": "Payment Webhooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Starter', 'Professional', 'Enterprise'.",
                        max_length=100,
                        unique=True,
                        verbose_name="package name",
                    ),
                ),
                (
                    "token_count",
                    models.PositiveIntegerField(
                        help_text="Number of tokens credited to the wallet on successful purchase.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="token count",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price before GST, in the platform's base currency.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="price",
                    ),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        help_text="GST rate applied to price, e.g. 18.00 for 18%.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="GST percentage",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Optional promotional discount applied to price before GST.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="discount percentage",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive packages are hidden from purchase but preserved for historical orders.",
                        verbose_name="is active",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first in package listings.",
                        verbose_name="sort order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Package",
                "verbose_name_plural": "Token Packages",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("token_purchase", "Token Purchase"),
                            ("subscription", "Subscription"),
                        ],
                        db_index=True,
                        default="token_purchase",
                        max_length=20,
                        verbose_name="payment type",
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Razorpay order id",
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Populated once Razorpay confirms the payment (not present at order-creation time).",
                        max_length=100,
                        null=True,
                        verbose_name="Razorpay payment id",
                    ),
                ),
                (
                    "razorpay_signature",
                    models.CharField(
                        blank=True,
                        help_text="The signature submitted for verification - stored for audit purposes.",
                        max_length=255,
                        null=True,
                        verbose_name="Razorpay signature",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The exact amount charged (TokenPackage.final_price at time of purchase).",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "token_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Snapshot of TokenPackage.token_count at time of purchase - only set when payment_type=TOKEN_PURCHASE.",
                        null=True,
                        verbose_name="token count",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="failure reason",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
