# Generated by Django 5.0.6 on 2026-08-12 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("subscriptions", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when payment_type=SUBSCRIPTION.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="teacher",
            field=models.ForeignKey(
                help_text="The Teacher making this payment. Students never make payments.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who last updated this record, if known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentwebhook",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record, if known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentwebhook",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                help_text="The Payment this webhook relates to, if it could be matched.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_events",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentwebhook",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who last updated this record, if known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tokenpackage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record, if known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tokenpackage",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who last updated this record, if known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="token_package",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when payment_type=TOKEN_PURCHASE.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.tokenpackage",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["teacher", "status"], name="payments_pa_teacher_d414d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="payments_pa_status_343680_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("payment_type", "token_purchase"),
                        ("subscription_plan__isnull", True),
                        ("token_package__isnull", False),
                    ),
                    models.Q(
                        ("payment_type", "subscription"),
                        ("subscription_plan__isnull", False),
                        ("token_package__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="payment_type_matches_target",
            ),
        ),
    ]
