# Generated by Django 5.0.6 on 2026-09-01 07:53

import apps.utils.validators
import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenpackage",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Optional promotional discount applied to price before GST.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="discount percentage",
            ),
        ),
        migrations.AlterField(
            model_name="tokenpackage",
            name="gst_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("18.00"),
                help_text="GST rate applied to price, e.g. 18.00 for 18%.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="GST percentage",
            ),
        ),
        migrations.AlterField(
            model_name="tokenpackage",
            name="name",
            field=models.CharField(
                help_text="e.g. 'Starter', 'Professional', 'Enterprise'.",
                max_length=100,
                unique=True,
                validators=[apps.utils.validators.validate_taxonomy_name],
                verbose_name="package name",
            ),
        ),
        migrations.AlterField(
            model_name="tokenpackage",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base price before GST, in the platform's base currency.",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1000000.00")),
                ],
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="tokenpackage",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lower numbers appear first in package listings.",
                validators=[django.core.validators.MaxValueValidator(100000)],
                verbose_name="sort order",
            ),
        ),
        migrations.AlterField(
            model_name="tokenpackage",
            name="token_count",
            field=models.PositiveIntegerField(
                help_text="Number of tokens credited to the wallet on successful purchase.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000000),
                ],
                verbose_name="token count",
            ),
        ),
        migrations.AddConstraint(
            model_name="tokenpackage",
            constraint=models.CheckConstraint(
                check=models.Q(("name__regex", "^\\s*$"), _negated=True),
                name="token_package_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="tokenpackage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("token_count__gte", 1),
                    ("token_count__lte", 1000000),
                    ("price__gte", Decimal("0.00")),
                    ("price__lte", Decimal("1000000.00")),
                    ("gst_percentage__gte", Decimal("0.00")),
                    ("gst_percentage__lte", Decimal("100.00")),
                    ("discount_percentage__gte", Decimal("0.00")),
                    ("discount_percentage__lte", Decimal("100.00")),
                ),
                name="token_package_sane_ranges",
            ),
        ),
    ]
