# Generated by Django 5.0.14 on 2026-09-02 11:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_tokenpackage_discount_percentage_and_more"),
        ("teachers", "0004_alter_teacher_profile_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInstrumentSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("upi", "UPI"),
                            ("wallet", "Wallet"),
                            ("netbanking", "Netbanking"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("value_hash", models.CharField(db_index=True, max_length=64)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_instruments",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment instrument signature",
                "verbose_name_plural": "Payment instrument signatures",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "value_hash"],
                        name="payments_pa_kind_7e25f3_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="paymentinstrumentsignature",
            constraint=models.UniqueConstraint(
                fields=("teacher", "kind", "value_hash"),
                name="payment_instrument_unique_per_teacher",
            ),
        ),
    ]
