# Generated by Django 5.0.14 on 2026-09-02 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_reconciliationrun_paymentdispute"),
        ("wallet", "0002_wallethold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdispute",
            name="wallet_hold",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disputes",
                to="wallet.wallethold",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationrun",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record, if known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationrun",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who last updated this record, if known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdispute",
            index=models.Index(
                fields=["status", "created_at"], name="payments_pa_status_fe6f50_idx"
            ),
        ),
    ]
