# Generated by Django 5.0.14 on 2026-09-24 11:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_reprice_five_unlock_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The pre-GST amount this purchase is based on (TokenPackage.discounted_price, or SubscriptionPlan.monthly_price which has no GST concept) - what apps.commissions splits 2/3-1/3 with a referring Learning Partner. Null only for Payment rows created before apps.commissions existed.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='base amount'),
        ),
    ]
