# Generated by Django 5.0.14 on 2026-09-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_payment_base_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="instrument_hint",
            field=models.CharField(
                blank=True,
                help_text="A masked, human-readable hint of the instrument used, e.g. 'UPI - user@okhdfcbank' or 'Card - Visa •••4242'. Razorpay never exposes a full card/account number in the webhook payload (PCI-tokenized), so no further masking is needed here.",
                max_length=60,
                null=True,
                verbose_name="instrument hint",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="Razorpay's payment method for this transaction - 'card', 'upi', 'netbanking', 'wallet', etc. Populated from the payment.captured webhook payload; null until that webhook is processed.",
                max_length=20,
                null=True,
                verbose_name="payment method",
            ),
        ),
    ]
