# Generated by Django 5.0.14 on 2026-09-24 13:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lead_engine", "0007_lead_rejected_at_alter_lead_status"),
        ("payments", "0009_payment_base_amount"),
        ("subscriptions", "0008_subscriptionplan_bonus_leads"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("token_package", "Token Package"),
                            ("subscription_plan", "Subscription Plan"),
                            ("lead_unlock_pricing", "Lead Unlock Pricing"),
                        ],
                        max_length=20,
                        verbose_name="target type",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Which field this request changes - 'price', 'monthly_price', or 'token_cost'.",
                        max_length=30,
                        verbose_name="field name",
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of the target's value at request time.",
                        max_digits=12,
                        verbose_name="current value",
                    ),
                ),
                (
                    "requested_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="requested value",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=500, verbose_name="note"),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Super Admin who approved or rejected this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing_change_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead_unlock_pricing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_requests",
                        to="lead_engine.leadunlockpricing",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_requests",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "token_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_requests",
                        to="payments.tokenpackage",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Change Request",
                "verbose_name_plural": "Pricing Change Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="finance_pri_status_310131_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pricingchangerequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("lead_unlock_pricing__isnull", True),
                        ("subscription_plan__isnull", True),
                        ("token_package__isnull", False),
                    ),
                    models.Q(
                        ("lead_unlock_pricing__isnull", True),
                        ("subscription_plan__isnull", False),
                        ("token_package__isnull", True),
                    ),
                    models.Q(
                        ("lead_unlock_pricing__isnull", False),
                        ("subscription_plan__isnull", True),
                        ("token_package__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="pricing_change_request_exactly_one_target",
            ),
        ),
    ]
