# Generated by Django 5.0.6 on 2026-08-11 07:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages", "0001_initial"),
        ("location", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "student_class",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Grade 10', '1st Year B.Com', 'Adult Learner'.",
                        max_length=50,
                        null=True,
                        verbose_name="class",
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="budget (min)",
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="budget (max)",
                    ),
                ),
                (
                    "teaching_mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("both", "Both"),
                        ],
                        db_index=True,
                        default="both",
                        max_length=10,
                        verbose_name="teaching mode",
                    ),
                ),
                (
                    "preferred_timing",
                    models.CharField(
                        blank=True,
                        help_text="Free-text description, e.g. 'Weekday evenings after 6pm'.",
                        max_length=255,
                        null=True,
                        verbose_name="preferred timing",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about what the student is looking for.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("matched", "Matched"),
                            ("closed", "Closed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for Offline/Both teaching mode; optional for purely Online requirements.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirements",
                        to="location.city",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preferred_language",
                    models.ForeignKey(
                        blank=True,
                        help_text="The student's preferred language of instruction.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirements",
                        to="languages.language",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The Student who submitted this requirement.",
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject the student needs help with.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requirements",
                        to="subjects.subject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Requirement",
                "verbose_name_plural": "Student Requirements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "subject"],
                        name="student_req_status_f30335_idx",
                    ),
                    models.Index(
                        fields=["status", "teaching_mode"],
                        name="student_req_status_feff15_idx",
                    ),
                    models.Index(
                        fields=["student", "status"],
                        name="student_req_student_eafd29_idx",
                    ),
                ],
            },
        ),
    ]
