# Generated by Django 5.0.6 on 2026-08-13 12:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_requirement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrequirement",
            name="class_duration_minutes",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (30, "30 minutes"),
                    (45, "45 minutes"),
                    (60, "60 minutes"),
                    (90, "90 minutes"),
                    (120, "120 minutes"),
                ],
                default=60,
                help_text="Requested class length. Custom durations (not in the preset list) are supported by simply storing any positive integer - the choices above are UI suggestions, not a hard database constraint, matching the spec's 'or custom duration' allowance.",
                verbose_name="class duration (minutes)",
            ),
        ),
        migrations.CreateModel(
            name="StudentScheduleException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="reason"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="student_requirement.studentrequirement",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Schedule Exception",
                "verbose_name_plural": "Student Schedule Exceptions",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["student_requirement", "date"],
                        name="idx_student_exception_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentSchedulePreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        db_index=True,
                        verbose_name="day of week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
                (
                    "timezone",
                    models.CharField(
                        help_text="IANA timezone name, e.g. 'Asia/Kolkata'.",
                        max_length=64,
                        verbose_name="timezone",
                    ),
                ),
                (
                    "flexibility",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("flexible", "Flexible")],
                        default="flexible",
                        help_text="FIXED: little/no overlap heavily penalizes a teacher's time score. FLEXIBLE: partial overlap can still score reasonably.",
                        max_length=10,
                        verbose_name="flexibility",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High Priority"),
                            ("medium", "Medium Priority"),
                            ("low", "Low Priority"),
                        ],
                        default="medium",
                        help_text="Relative importance of this slot when the student has multiple preferences.",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_preferences",
                        to="student_requirement.studentrequirement",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Schedule Preference",
                "verbose_name_plural": "Student Schedule Preferences",
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["student_requirement", "day_of_week"],
                        name="idx_student_pref_lookup",
                    ),
                    models.Index(fields=["day_of_week"], name="idx_pref_day_analytics"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="studentschedulepreference",
            constraint=models.UniqueConstraint(
                fields=(
                    "student_requirement",
                    "day_of_week",
                    "start_time",
                    "end_time",
                    "timezone",
                ),
                name="unique_student_preference_window",
            ),
        ),
    ]
