# Generated by Django 5.0.6 on 2026-08-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0001_initial"),
        (
            "student_requirement",
            "0002_studentrequirement_class_duration_minutes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrequirement",
            name="pincode_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Structured pincode for offline distance matching, distinct from city (free-text/FK reference).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requirements",
                to="matching.pincodelocation",
            ),
        ),
    ]
