# Generated by Django 5.0.6 on 2026-08-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_requirement", "0003_studentrequirement_pincode_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrequirement",
            name="lead_distribution_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                help_text="Progress of the async lead generation/distribution job for this requirement.",
                max_length=12,
                verbose_name="lead distribution status",
            ),
        ),
    ]
