# Generated by Django 5.0.6 on 2026-09-01 06:45

import apps.utils.validators
import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
        ("location", "0001_initial"),
        ("matching", "0002_alter_pincodelocation_pincode"),
        ("student_requirement", "0004_studentrequirement_lead_distribution_status"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrequirement",
            name="budget_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1000000.00")),
                ],
                verbose_name="budget (max)",
            ),
        ),
        migrations.AlterField(
            model_name="studentrequirement",
            name="budget_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1000000.00")),
                ],
                verbose_name="budget (min)",
            ),
        ),
        migrations.AlterField(
            model_name="studentrequirement",
            name="class_duration_minutes",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (30, "30 minutes"),
                    (45, "45 minutes"),
                    (60, "60 minutes"),
                    (90, "90 minutes"),
                    (120, "120 minutes"),
                ],
                default=60,
                help_text="Requested class length in minutes. The choices above are UI suggestions; any value from 15 to 480 minutes is accepted.",
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(480),
                ],
                verbose_name="class duration (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="studentrequirement",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Additional details about what the student is looking for.",
                max_length=2000,
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="studentrequirement",
            name="preferred_timing",
            field=models.CharField(
                blank=True,
                help_text="Free-text description, e.g. 'Weekday evenings after 6pm'.",
                max_length=255,
                null=True,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="preferred timing",
            ),
        ),
        migrations.AlterField(
            model_name="studentrequirement",
            name="student_class",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'Grade 10', '1st Year B.Com', 'Adult Learner'.",
                max_length=50,
                null=True,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="class",
            ),
        ),
        migrations.AlterField(
            model_name="studentscheduleexception",
            name="reason",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentrequirement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("budget_min__isnull", True),
                    ("budget_max__isnull", True),
                    ("budget_min__lte", models.F("budget_max")),
                    _connector="OR",
                ),
                name="requirement_budget_min_lte_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentrequirement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("class_duration_minutes__gte", 15),
                    ("class_duration_minutes__lte", 480),
                ),
                name="requirement_class_duration_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentrequirement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("student_class__isnull", True),
                        models.Q(("student_class__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("preferred_timing__isnull", True),
                        models.Q(("preferred_timing__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("description__isnull", True),
                        models.Q(("description__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                ),
                name="requirement_text_fields_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentscheduleexception",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("reason__isnull", True),
                    models.Q(("reason__regex", "^\\s*$"), _negated=True),
                    _connector="OR",
                ),
                name="student_exception_reason_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentschedulepreference",
            constraint=models.CheckConstraint(
                check=models.Q(("start_time__lt", models.F("end_time"))),
                name="student_pref_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentschedulepreference",
            constraint=models.CheckConstraint(
                check=models.Q(("timezone__regex", "^\\s*$"), _negated=True),
                name="student_pref_timezone_not_blank",
            ),
        ),
    ]
