# Generated by Django 5.0.14 on 2026-09-02 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_requirement", "0005_alter_studentrequirement_budget_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrequirement",
            name="class_duration_minutes",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (30, "30 minutes"),
                    (45, "45 minutes"),
                    (60, "60 minutes"),
                    (90, "90 minutes"),
                    (120, "120 minutes"),
                ],
                default=60,
                help_text="Requested class length in minutes. One of the preset values (30 / 45 / 60 / 90 / 120); the API rejects other values. The range validators + DB CHECK (15-480) are a floor/ceiling guard for any non-API write path.",
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(480),
                ],
                verbose_name="class duration (minutes)",
            ),
        ),
    ]
