# Generated by Django 5.0.14 on 2026-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_requirement", "0006_sync_class_duration_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrequirement",
            name="lead_distribution_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("held", "Held for review"),
                ],
                db_index=True,
                default="pending",
                help_text="Progress of the async lead generation/distribution job for this requirement.",
                max_length=12,
                verbose_name="lead distribution status",
            ),
        ),
    ]
