# Generated by Django 5.0.14 on 2026-09-16 00:00

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_requirement", "0007_alter_studentrequirement_lead_distribution_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrequirement",
            name="budget_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text=(
                    "The low end of what the student can pay per month. "
                    "Compared against a teacher's monthly_rate in "
                    "MatchingService - see "
                    "apps.teacher_profile.models.TeacherProfile.monthly_rate."
                ),
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("10000000.00")),
                ],
                verbose_name="budget (min, per month)",
            ),
        ),
        migrations.AlterField(
            model_name="studentrequirement",
            name="budget_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text=(
                    "The high end of what the student can pay per month. "
                    "Compared against a teacher's monthly_rate in "
                    "MatchingService - see "
                    "apps.teacher_profile.models.TeacherProfile.monthly_rate."
                ),
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("10000000.00")),
                ],
                verbose_name="budget (max, per month)",
            ),
        ),
    ]
