# Generated by Django 5.0.14 on 2026-09-16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_ranked_languages(apps, schema_editor):
    """
    Preserves the exact old semantics under the new shape: a requirement
    that had preferred_language set becomes a single rank-1 entry; a
    requirement that had it null (== "no preference", the old behaviour of
    MatchingService._language_score / LanguageMatchingService.match_by_id)
    becomes no_language_preference=True, so existing data keeps matching
    the same teachers it did before this migration.
    """
    StudentRequirement = apps.get_model("student_requirement", "StudentRequirement")
    StudentRequirementLanguage = apps.get_model(
        "student_requirement", "StudentRequirementLanguage"
    )

    to_create = []
    no_pref_ids = []
    for req in StudentRequirement.objects.all().only("id", "preferred_language_id"):
        if req.preferred_language_id:
            to_create.append(
                StudentRequirementLanguage(
                    student_requirement_id=req.id,
                    language_id=req.preferred_language_id,
                    rank=1,
                )
            )
        else:
            no_pref_ids.append(req.id)

    if to_create:
        StudentRequirementLanguage.objects.bulk_create(to_create)
    if no_pref_ids:
        StudentRequirement.objects.filter(id__in=no_pref_ids).update(
            no_language_preference=True
        )


def unbackfill_ranked_languages(apps, schema_editor):
    StudentRequirement = apps.get_model("student_requirement", "StudentRequirement")
    StudentRequirementLanguage = apps.get_model(
        "student_requirement", "StudentRequirementLanguage"
    )
    for req in StudentRequirement.objects.all().only("id"):
        top = (
            StudentRequirementLanguage.objects.filter(student_requirement_id=req.id)
            .order_by("rank")
            .first()
        )
        req.preferred_language_id = top.language_id if top else None
        req.save(update_fields=["preferred_language"])


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
        ("student_requirement", "0008_alter_studentrequirement_budget_min_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrequirement",
            name="no_language_preference",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Explicitly set when the student picked 'Any language' "
                    "instead of ranking specific ones. Mutually exclusive "
                    "with having any StudentRequirementLanguage rows - "
                    "enforced in the write serializer, same 'flexible vs "
                    "specific' shape as StudentSchedulePreference's "
                    "flexibility field. Language is a mandatory choice: "
                    "every requirement has either this set True or at "
                    "least one ranked language."
                ),
                verbose_name="any language is fine",
            ),
        ),
        migrations.CreateModel(
            name="StudentRequirementLanguage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        help_text="1-based preference order - 1 is most preferred.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rank",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="languages.language",
                    ),
                ),
                (
                    "student_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_languages",
                        to="student_requirement.studentrequirement",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Preferred Language",
                "verbose_name_plural": "Student Preferred Languages",
                "ordering": ["rank"],
            },
        ),
        migrations.AddConstraint(
            model_name="studentrequirementlanguage",
            constraint=models.UniqueConstraint(
                fields=("student_requirement", "rank"),
                name="requirement_language_rank_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentrequirementlanguage",
            constraint=models.UniqueConstraint(
                fields=("student_requirement", "language"),
                name="requirement_language_unique",
            ),
        ),
        migrations.RunPython(
            backfill_ranked_languages, unbackfill_ranked_languages
        ),
        migrations.RemoveField(
            model_name="studentrequirement",
            name="preferred_language",
        ),
    ]
