# Generated by Django 5.0.14 on 2026-09-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_requirement', '0009_ranked_preferred_languages'),
        ('teachers', '0006_remove_teacher_teacher_text_fields_not_blank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequirement',
            name='offer_teacher',
            field=models.ForeignKey(blank=True, help_text="Set only for a direct 'Learn with this teacher' offer - targets exactly this one teacher instead of the general matching pool. Non-null is what makes this a direct offer; never settable through the normal requirement create/update serializer, only through DirectOfferCreateView.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_offers', to='teachers.teacher'),
        ),
    ]
