# Generated by Django 5.0.6 on 2026-08-06 07:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teachers/profile_photos/%Y/%m/",
                        verbose_name="profile photo",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Short description of teaching style, background, and specialties.",
                        null=True,
                        verbose_name="bio",
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Total years of teaching experience.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(80),
                        ],
                        verbose_name="years of experience",
                    ),
                ),
                (
                    "qualification_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "High School"),
                            ("diploma", "Diploma"),
                            ("bachelors", "Bachelor's Degree"),
                            ("masters", "Master's Degree"),
                            ("doctorate", "Doctorate (PhD)"),
                            (
                                "professional_certification",
                                "Professional Certification",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="qualification level",
                    ),
                ),
                (
                    "qualification_detail",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'M.Sc. Mathematics, Delhi University'.",
                        max_length=255,
                        null=True,
                        verbose_name="qualification detail",
                    ),
                ),
                (
                    "subjects_taught",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of subjects this teacher can teach.",
                        max_length=500,
                        null=True,
                        verbose_name="subjects taught",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="city"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="state"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="country"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The User account this teacher profile belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["city", "qualification_level"],
                        name="teachers_te_city_d41ba7_idx",
                    ),
                    models.Index(
                        fields=["experience_years"],
                        name="teachers_te_experie_1e3741_idx",
                    ),
                ],
            },
        ),
    ]
