# Generated by Django 5.0.6 on 2026-08-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="pincode_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Structured pincode/location for offline distance matching. Distinct from the free-text city/state/country fields above - this is what LocationMatchingService actually queries against.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="matching.pincodelocation",
            ),
        ),
    ]
