# Generated by Django 5.0.6 on 2026-09-01 06:52

import apps.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_alter_pincodelocation_pincode"),
        ("teachers", "0002_teacher_pincode_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="bio",
            field=models.CharField(
                blank=True,
                help_text="Short description of teaching style, background, and specialties.",
                max_length=2000,
                null=True,
                verbose_name="bio",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[apps.utils.validators.validate_place_name],
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="country",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[apps.utils.validators.validate_place_name],
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="qualification_detail",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'M.Sc. Mathematics, Delhi University'.",
                max_length=255,
                null=True,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="qualification detail",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="state",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[apps.utils.validators.validate_place_name],
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subjects_taught",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of subjects this teacher can teach.",
                max_length=500,
                null=True,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="subjects taught",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("bio__isnull", True),
                        models.Q(("bio__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("qualification_detail__isnull", True),
                        models.Q(
                            ("qualification_detail__regex", "^\\s*$"), _negated=True
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        ("subjects_taught__isnull", True),
                        models.Q(("subjects_taught__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("city__isnull", True),
                        models.Q(("city__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("state__isnull", True),
                        models.Q(("state__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("country__isnull", True),
                        models.Q(("country__regex", "^\\s*$"), _negated=True),
                        _connector="OR",
                    ),
                ),
                name="teacher_text_fields_not_blank",
            ),
        ),
    ]
