# Generated by Django 5.0.14 on 2026-09-14 11:11

import apps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Required to pass verification (see VerificationService.PROFILE_BASICS) - a teacher without one can never clear the floor that unlocks leads/search.', null=True, upload_to='teachers/profile_photos/%Y/%m/', validators=[apps.utils.validators.validate_image_upload], verbose_name='profile photo'),
        ),
    ]
