# Generated by Django 5.0.14 on 2026-09-16 11:47

import apps.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_alter_languagealias_alias_text_and_more'),
        ('teachers', '0005_alter_teacher_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacher',
            name='teacher_text_fields_not_blank',
        ),
        migrations.AddField(
            model_name='teacher',
            name='address_line1',
            field=models.CharField(blank=True, help_text='House/flat no., building, street - required once teaching_mode is Offline or Both (see TeacherCreateUpdateSerializer.validate).', max_length=255, null=True, validators=[apps.utils.validators.validate_no_control_characters], verbose_name='address line 1'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Area, landmark - optional.', max_length=255, null=True, validators=[apps.utils.validators.validate_no_control_characters], verbose_name='address line 2'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pincode',
            field=models.CharField(blank=True, help_text='6-digit PIN code, resolved to pincode_location below on save (see TeacherCreateUpdateSerializer._resolve_pincode).', max_length=6, null=True, validators=[apps.utils.validators.validate_pincode], verbose_name='PIN code'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bio__isnull', True), models.Q(('bio__regex', '^\\s*$'), _negated=True), _connector='OR'), models.Q(('qualification_detail__isnull', True), models.Q(('qualification_detail__regex', '^\\s*$'), _negated=True), _connector='OR'), models.Q(('subjects_taught__isnull', True), models.Q(('subjects_taught__regex', '^\\s*$'), _negated=True), _connector='OR'), models.Q(('city__isnull', True), models.Q(('city__regex', '^\\s*$'), _negated=True), _connector='OR'), models.Q(('state__isnull', True), models.Q(('state__regex', '^\\s*$'), _negated=True), _connector='OR'), models.Q(('country__isnull', True), models.Q(('country__regex', '^\\s*$'), _negated=True), _connector='OR'), models.Q(('address_line1__isnull', True), models.Q(('address_line1__regex', '^\\s*$'), _negated=True), _connector='OR'), models.Q(('address_line2__isnull', True), models.Q(('address_line2__regex', '^\\s*$'), _negated=True), _connector='OR')), name='teacher_text_fields_not_blank'),
        ),
    ]
