# Generated by Django 5.0.6 on 2026-09-01 07:45

import apps.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=150,
                validators=[apps.utils.validators.validate_place_name],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="ISO 3166-1 alpha-2 or alpha-3 country code, e.g. 'IN', 'US'.",
                max_length=3,
                unique=True,
                validators=[apps.utils.validators.validate_country_code],
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=150,
                unique=True,
                validators=[apps.utils.validators.validate_place_name],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Optional short state code, e.g. 'MH', 'CA'.",
                max_length=10,
                null=True,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=150,
                validators=[apps.utils.validators.validate_place_name],
                verbose_name="name",
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.CheckConstraint(
                check=models.Q(("name__regex", "^\\s*$"), _negated=True),
                name="city_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.CheckConstraint(
                check=models.Q(("name__regex", "^\\s*$"), _negated=True),
                name="country_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.CheckConstraint(
                check=models.Q(("code__regex", "^[A-Z]{2,3}$")),
                name="country_code_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.CheckConstraint(
                check=models.Q(("name__regex", "^\\s*$"), _negated=True),
                name="state_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("code__isnull", True),
                    models.Q(("code__regex", "^\\s*$"), _negated=True),
                    _connector="OR",
                ),
                name="state_code_not_blank",
            ),
        ),
    ]
