# Generated by Django 5.0.14 on 2026-09-02 06:47

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualReviewItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("teacher_verification", "Teacher verification"),
                            ("duplicate_account", "Duplicate account"),
                            ("lead_quality", "Fake / unreachable lead"),
                            ("payment_dispute", "Payment dispute"),
                            ("content_flag", "Flagged content"),
                            ("user_report", "User report"),
                            ("reconciliation", "Payment reconciliation drift"),
                            ("anomaly", "Anomaly alert"),
                            ("risk_escalation", "Risk escalation"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=3)),
                ("summary", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "dedupe_key",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("resolution", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_items_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_items_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual review item",
                "verbose_name_plural": "Manual review queue",
                "ordering": ["priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "kind", "priority"],
                        name="trust_manua_status_eedddc_idx",
                    ),
                    models.Index(
                        fields=["kind", "dedupe_key"],
                        name="trust_manua_kind_d4d8e4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "verification_score",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000")),
                            django.core.validators.MaxValueValidator(Decimal("1.000")),
                        ],
                        verbose_name="verification score",
                    ),
                ),
                (
                    "is_fully_verified",
                    models.BooleanField(
                        default=False, verbose_name="fully verified badge"
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="risk score",
                    ),
                ),
                (
                    "risk_state",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("limited", "Limited"),
                            ("review", "Under review"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=12,
                        verbose_name="risk state",
                    ),
                ),
                (
                    "lead_quality_score",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000")),
                            django.core.validators.MaxValueValidator(Decimal("1.000")),
                        ],
                        verbose_name="lead quality score",
                    ),
                ),
                (
                    "verification_recomputed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("risk_recomputed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust profile",
                "verbose_name_plural": "Trust profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["risk_state", "-created_at"],
                        name="trust_trust_risk_st_bc8b98_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="trustprofile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("verification_score__gte", 0), ("verification_score__lte", 1)
                ),
                name="trust_profile_verification_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="trustprofile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("lead_quality_score__gte", 0), ("lead_quality_score__lte", 1)
                ),
                name="trust_profile_lead_quality_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="trustprofile",
            constraint=models.CheckConstraint(
                check=models.Q(("risk_score__gte", 0), ("risk_score__lte", 100)),
                name="trust_profile_risk_score_range",
            ),
        ),
    ]
