# Generated by Django 5.0.14 on 2026-09-02 07:47

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0002_otpchallenge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpchallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("verify_email", "Verify email address"),
                    ("verify_mobile", "Verify mobile number"),
                    ("sensitive_change", "Confirm a sensitive account change"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SensitiveChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("email", "Email address"),
                            ("mobile", "Mobile number"),
                            ("password", "Password"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        blank=True,
                        help_text="New email / mobile (not used for password).",
                        max_length=255,
                    ),
                ),
                (
                    "new_secret_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hashed new password (password changes only).",
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("awaiting_otp", "Awaiting code confirmation"),
                            ("scheduled", "Scheduled (cooldown running)"),
                            ("applied", "Applied"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="awaiting_otp",
                        max_length=16,
                    ),
                ),
                ("apply_after", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("requested_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sensitive_changes",
                        to="trust.otpchallenge",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitive_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensitive change request",
                "verbose_name_plural": "Sensitive change requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "field", "state"],
                        name="trust_sensi_user_id_74d154_idx",
                    ),
                    models.Index(
                        fields=["state", "apply_after"],
                        name="trust_sensi_state_e31567_idx",
                    ),
                ],
            },
        ),
    ]
