# Generated by Django 5.0.14 on 2026-09-02 08:40

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0003_alter_otpchallenge_purpose_sensitivechangerequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentitySignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("phone", "Normalised phone number"),
                            ("email", "Canonicalised email address"),
                            ("device", "Client device fingerprint"),
                            ("id_number", "Government ID number"),
                            ("selfie_hash", "Selfie perceptual hash"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("value_hash", models.CharField(db_index=True, max_length=64)),
                ("source", models.CharField(blank=True, max_length=40)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity signature",
                "verbose_name_plural": "Identity signatures",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DuplicateSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("phone", "Normalised phone number"),
                            ("email", "Canonicalised email address"),
                            ("device", "Client device fingerprint"),
                            ("id_number", "Government ID number"),
                            ("selfie_hash", "Selfie perceptual hash"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value_hash", models.CharField(max_length=64)),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matched_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_by_duplicate_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicate_signals",
                        to="trust.manualreviewitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Duplicate signal",
                "verbose_name_plural": "Duplicate signals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "resolved"],
                        name="trust_dupli_user_id_5f8693_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="duplicatesignal",
            constraint=models.UniqueConstraint(
                fields=("user", "matched_user", "kind"),
                name="duplicate_signal_unique_pair_kind",
            ),
        ),
        migrations.AddIndex(
            model_name="identitysignature",
            index=models.Index(
                fields=["kind", "value_hash"], name="trust_ident_kind_39f56d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="identitysignature",
            constraint=models.UniqueConstraint(
                fields=("user", "kind", "value_hash"),
                name="identity_signature_unique_per_user_kind",
            ),
        ),
    ]
