# Generated by Django 5.0.14 on 2026-09-02 09:00

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0004_alter_teacher_profile_photo"),
        ("trust", "0004_identitysignature_duplicatesignal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherVerificationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("profile_basics", "Basic profile completed"),
                            ("subjects_set", "Subjects selected"),
                            ("availability_set", "Availability added"),
                            ("email_verified", "Email verified"),
                            ("mobile_verified", "Mobile verified"),
                            ("gov_id", "Government photo ID"),
                            ("selfie_liveness", "Selfie / liveness"),
                            ("address_proof", "Address proof"),
                            ("video_interview", "Onboarding video call"),
                            ("bank_penny_drop", "Bank account (payouts)"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Not started"),
                            ("submitted", "Submitted, under review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField(default=0)),
                ("is_auto", models.BooleanField(default=False)),
                ("evidence_ref", models.CharField(blank=True, max_length=255)),
                ("provider_ref", models.CharField(blank=True, max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_verification_items",
                        to="trust.manualreviewitem",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_verification_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_items",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher verification item",
                "verbose_name_plural": "Teacher verification items",
                "ordering": ["teacher_id", "key"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "status"],
                        name="trust_teach_teacher_55a7fa_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="teacherverificationitem",
            constraint=models.UniqueConstraint(
                fields=("teacher", "key"),
                name="teacher_verification_item_unique_per_key",
            ),
        ),
    ]
