# Generated by Django 5.0.14 on 2026-09-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0008_alter_risksignal_kind_userreport_contentflag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustprofile",
            name="known_countries",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
