# Generated by Django 5.0.14 on 2026-09-03 08:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0009_trustprofile_known_countries"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualreviewitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("teacher_verification", "Teacher verification"),
                    ("duplicate_account", "Duplicate account"),
                    ("lead_quality", "Fake / unreachable lead"),
                    ("payment_dispute", "Payment dispute"),
                    ("payment_risk", "Payment risk"),
                    ("content_flag", "Flagged content"),
                    ("user_report", "User report"),
                    ("reconciliation", "Payment reconciliation drift"),
                    ("anomaly", "Anomaly alert"),
                    ("risk_escalation", "Risk escalation"),
                    ("suspension_appeal", "Suspension appeal"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SuspensionAppeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                ("message", models.TextField(max_length=4000)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("risk_score_at_submit", models.PositiveSmallIntegerField(default=0)),
                ("risk_state_at_submit", models.CharField(blank=True, max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("in_review", "Under review"),
                            ("granted", "Approved - access restored"),
                            ("denied", "Declined"),
                            ("withdrawn", "Withdrawn by the account holder"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("requested_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspension_appeals_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspension_appeals",
                        to="trust.manualreviewitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspension_appeals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Suspension appeal",
                "verbose_name_plural": "Suspension appeals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="trust_suspe_user_id_c42f89_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="trust_suspe_status_9d5e17_idx",
                    ),
                ],
            },
        ),
    ]
