# Generated by Django 5.0.14 on 2026-09-07 07:33

import apps.utils.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0010_alter_manualreviewitem_kind_suspensionappeal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherVerificationEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "pose",
                    models.CharField(
                        choices=[
                            ("document_front", "Document - front"),
                            ("document_back", "Document - back"),
                            ("document", "Document"),
                            ("selfie_center", "Selfie - looking straight ahead"),
                            ("selfie_left", "Selfie - looking left"),
                            ("selfie_right", "Selfie - looking right"),
                            ("selfie_up", "Selfie - looking up"),
                            ("selfie_down", "Selfie - looking down"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to="teachers/verification/%Y/%m/",
                        validators=[apps.utils.validators.validate_image_upload],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_files",
                        to="trust.teacherverificationitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher verification evidence",
                "verbose_name_plural": "Teacher verification evidence",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["item"], name="trust_teach_item_id_54a214_idx")
                ],
            },
        ),
    ]
