# Generated by Django 5.0.14 on 2026-09-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0012_onboardingcallrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualreviewitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("teacher_verification", "Teacher verification"),
                    ("duplicate_account", "Duplicate account"),
                    ("lead_quality", "Fake / unreachable lead"),
                    ("payment_dispute", "Payment dispute"),
                    ("payment_risk", "Payment risk"),
                    ("content_flag", "Flagged content"),
                    ("user_report", "User report"),
                    ("reconciliation", "Payment reconciliation drift"),
                    ("anomaly", "Anomaly alert"),
                    ("risk_escalation", "Risk escalation"),
                    ("suspension_appeal", "Suspension appeal"),
                    ("support_ticket", "Support ticket / bug report"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
