# Generated by Django 5.0.14 on 2026-09-09 13:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0013_alter_manualreviewitem_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualreviewitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("teacher_verification", "Teacher verification"),
                    ("duplicate_account", "Duplicate account"),
                    ("lead_quality", "Fake / unreachable lead"),
                    ("fake_lead_report", "Fake lead reports"),
                    ("payment_dispute", "Payment dispute"),
                    ("payment_risk", "Payment risk"),
                    ("content_flag", "Flagged content"),
                    ("user_report", "User report"),
                    ("reconciliation", "Payment reconciliation drift"),
                    ("anomaly", "Anomaly alert"),
                    ("risk_escalation", "Risk escalation"),
                    ("suspension_appeal", "Suspension appeal"),
                    ("support_ticket", "Support ticket / bug report"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AccountSanction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("ban", "Ban"), ("suspend", "Suspension")],
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Super Admin action"),
                            (
                                "auto_fake_leads_weekly",
                                "Automatic - fake-lead reports (weekly threshold)",
                            ),
                            (
                                "auto_fake_leads_monthly",
                                "Automatic - fake-lead reports (monthly threshold)",
                            ),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("lifted_at", models.DateTimeField(blank=True, null=True)),
                ("lift_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Super Admin who applied it; null for an automatic ban.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_sanctions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lifted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_sanctions_lifted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_sanctions",
                        to="trust.manualreviewitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_sanctions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account sanction",
                "verbose_name_plural": "Account sanctions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "active"], name="trust_accou_user_id_8aa54d_idx"
                    ),
                    models.Index(
                        fields=["active", "-created_at"],
                        name="trust_accou_active_b1a8dc_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="accountsanction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("user",),
                name="account_sanction_one_active_per_user",
            ),
        ),
    ]
