# Generated by Django 5.0.14 on 2026-09-21 13:44

import apps.utils.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_language_learning_partner_alter_language_code_and_more'),
        ('subjects', '0005_subject_learning_partner_alter_subject_name_and_more'),
        ('trust', '0015_alter_accountsanction_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherverificationitem',
            name='key',
            field=models.CharField(choices=[('profile_basics', 'Profile photo, bio & qualification'), ('subjects_set', 'Subjects selected'), ('availability_set', 'Availability added'), ('email_verified', 'Email verified'), ('mobile_verified', 'Mobile verified'), ('gov_id', 'Government photo ID'), ('selfie_liveness', 'Selfie / liveness'), ('address_proof', 'Address proof'), ('video_interview', 'Onboarding video call'), ('bank_penny_drop', 'Bank account (payouts)')], db_index=True, max_length=24),
        ),
        migrations.CreateModel(
            name='LearningPartnerTaxonomyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted, if applicable.', null=True)),
                ('kind', models.CharField(choices=[('subject', 'Subject'), ('language', 'Language')], max_length=10, verbose_name='kind')),
                ('name', models.CharField(max_length=150, validators=[apps.utils.validators.validate_taxonomy_name], verbose_name='name')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='note')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=10, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('deny_reason', models.CharField(blank=True, max_length=500, verbose_name='deny reason')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('created_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='languages.language', verbose_name='created language')),
                ('created_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subjects.subject', verbose_name='created subject')),
                ('learning_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_requests', to=settings.AUTH_USER_MODEL, verbose_name='learning partner')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomy_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Partner taxonomy request',
                'verbose_name_plural': 'Learning Partner taxonomy requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='trust_learn_status_045cd1_idx')],
            },
        ),
    ]
