# Generated by Django 5.0.14 on 2026-09-22 06:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0016_alter_teacherverificationitem_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeLeadEndorsement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted, if applicable.', null=True)),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='note')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('learning_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_lead_endorsements_made', to=settings.AUTH_USER_MODEL, verbose_name='learning partner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_lead_endorsements', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fake-lead endorsement',
                'verbose_name_plural': 'Fake-lead endorsements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='fakeleadendorsement',
            constraint=models.UniqueConstraint(fields=('student', 'learning_partner'), name='one_endorsement_per_partner_per_student'),
        ),
    ]
