# Generated by Django 5.0.14 on 2026-09-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0017_fakeleadendorsement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsanction',
            name='source',
            field=models.CharField(choices=[('manual', 'Super Admin action'), ('manual_content_moderation', 'Content Moderation admin action'), ('auto_fake_leads_weekly', 'Automatic - fake-lead reports (weekly threshold)'), ('auto_fake_leads_monthly', 'Automatic - fake-lead reports (monthly threshold)'), ('auto_staff_login_bruteforce', 'Automatic - brute-force admin/super-admin login attempts')], db_index=True, default='manual', max_length=32),
        ),
    ]
