# Generated by Django 5.0.14 on 2026-09-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0018_alter_accountsanction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcallrequest',
            name='call_started_at',
            field=models.DateTimeField(blank=True, help_text='Set when a Support admin accepts the request - the moment the video call goes live for both sides. Null until then.', null=True),
        ),
    ]
