# Generated by Django 5.0.14 on 2026-09-24 11:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0009_payment_base_amount'),
        ('teachers', '0006_remove_teacher_teacher_text_fields_not_blank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPartnerBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted, if applicable.', null=True)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=34)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('learning_partner', models.OneToOneField(limit_choices_to={'role': 'learning_partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL, verbose_name='learning partner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Partner Bank Account',
                'verbose_name_plural': 'Learning Partner Bank Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPartnerWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted, if applicable.', null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current commission balance in rupees. NEVER set this directly - always go through LearningPartnerWalletService.credit()/debit(). May go negative after a reversal clawing back an already-paid-out commission - a real accounting state, not a bug.', max_digits=12, verbose_name='balance')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('learning_partner', models.OneToOneField(limit_choices_to={'role': 'learning_partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='commission_wallet', to=settings.AUTH_USER_MODEL, verbose_name='learning partner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Partner Wallet',
                'verbose_name_plural': 'Learning Partner Wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted, if applicable.', null=True)),
                ('payment_type', models.CharField(db_index=True, help_text='Denormalized copy of Payment.payment_type, for filtering.', max_length=20, verbose_name='payment type')),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='The pre-GST amount the 2/3 - 1/3 split is computed from (Payment.base_amount, snapshotted at order-creation time).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='base amount')),
                ('partner_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='round(base_amount * 2/3, 2). Zero when learning_partner is null.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='partner share')),
                ('business_share', models.DecimalField(decimal_places=2, help_text='payment.amount - partner_share. Always includes the full GST amount (GST is never split with a partner) plus, when there is a partner, 1/3 of the base price - or the full charged amount when there is no partner.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='business share')),
                ('status', models.CharField(choices=[('active', 'Active'), ('reversed', 'Reversed')], db_index=True, default='active', max_length=10, verbose_name='status')),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('learning_partner', models.ForeignKey(blank=True, help_text='The Learning Partner this commission was earned by - a snapshot of teacher.user.learning_partner at the moment the payment succeeded. Null when the teacher was not attributed to any partner, in which case the business kept the full amount and partner_share is 0.', limit_choices_to={'role': 'learning_partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_commissions', to=settings.AUTH_USER_MODEL, verbose_name='learning partner')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='payments.payment')),
                ('teacher', models.ForeignKey(help_text='Denormalized from payment.teacher for cheap reporting queries.', on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='teachers.teacher')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['learning_partner', 'status'], name='commissions_learnin_5a709d_idx'), models.Index(fields=['teacher', 'status'], name='commissions_teacher_40b31d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningPartnerWalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted, if applicable.', null=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('reversal', 'Reversal')], db_index=True, max_length=10, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Rupee amount involved in this transaction (always positive).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='balance after')),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='A Commission id (credit/reversal) or PayoutRequest id (debit) - not a foreign key since the reference type varies.', max_length=255, null=True, verbose_name='reference id')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='commissions.learningpartnerwallet')),
            ],
            options={
                'verbose_name': 'Learning Partner Wallet Transaction',
                'verbose_name_plural': 'Learning Partner Wallet Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'transaction_type'], name='commissions_wallet__9b3217_idx'), models.Index(fields=['wallet', 'created_at'], name='commissions_wallet__39515f_idx'), models.Index(fields=['reference_id'], name='commissions_referen_d5e879_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted, if applicable.', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='amount')),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=34)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], db_index=True, default='pending', max_length=10, verbose_name='status')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('payout_reference', models.CharField(blank=True, help_text='Bank transfer UTR / reference number, filled in at mark-paid time.', max_length=100, null=True, verbose_name='payout reference')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, help_text='The Admin/Super Admin who approved or rejected this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_decisions', to=settings.AUTH_USER_MODEL)),
                ('learning_partner', models.ForeignKey(limit_choices_to={'role': 'learning_partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL, verbose_name='learning partner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout Request',
                'verbose_name_plural': 'Payout Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['learning_partner', 'status'], name='commissions_learnin_913e5c_idx'), models.Index(fields=['status', 'created_at'], name='commissions_status_59bd45_idx')],
            },
        ),
    ]
