# Generated by Django 5.0.6 on 2026-08-11 07:25

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student_requirement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("viewed", "Viewed"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_viewed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the teacher has opened this lead's details at least once.",
                        verbose_name="is viewed",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="viewed at"
                    ),
                ),
                (
                    "contact_unlocked",
                    models.BooleanField(
                        default=False,
                        help_text="Always False in Phase 2. Unlocking (via token deduction) is implemented in Phase 3 - this field exists now purely so the schema is stable ahead of that phase.",
                        verbose_name="contact unlocked",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_requirement",
                    models.ForeignKey(
                        help_text="The student requirement this lead was generated from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="student_requirement.studentrequirement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
