# Generated by Django 5.0.6 on 2026-08-11 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lead_engine", "0001_initial"),
        ("teacher_profile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="teacher_profile",
            field=models.ForeignKey(
                help_text="The teacher profile matched to this requirement.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="teacher_profile.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who last updated this record, if known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["teacher_profile", "status"],
                name="lead_engine_teacher_a93d69_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["student_requirement", "status"],
                name="lead_engine_student_c7f9ef_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.UniqueConstraint(
                fields=("student_requirement", "teacher_profile"),
                name="unique_lead_per_requirement_teacher_pair",
            ),
        ),
    ]
