# Generated by Django 5.0.6 on 2026-08-13 12:11

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_engine", "0003_leadunlockpricing_leadunlockhistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadMatchScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "match_score",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Composite weighted score, 0-100. See settings.MATCHING_WEIGHTS for component weights.",
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="match score",
                    ),
                ),
                (
                    "subject_score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="subject score",
                    ),
                ),
                (
                    "time_score",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Time compatibility score, 0-100 - see TimeCompatibilityService for the overlap calculation.",
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="time score",
                    ),
                ),
                (
                    "language_score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="language score",
                    ),
                ),
                (
                    "location_score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="location score",
                    ),
                ),
                (
                    "budget_score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="budget score",
                    ),
                ),
                (
                    "rating_score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="rating score",
                    ),
                ),
                (
                    "experience_score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="experience score",
                    ),
                ),
                (
                    "verification_score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="verification score",
                    ),
                ),
                (
                    "response_rate_score",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Always 100 in this implementation - no teacher response-time tracking exists yet anywhere in this codebase. Stored now so the field/weight exists and a future phase can populate it with real data without a schema change. See matching_service.py.",
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="response rate score",
                    ),
                ),
                (
                    "premium_score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="premium score",
                    ),
                ),
                (
                    "best_matching_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="DayOfWeek value (1=Monday...7=Sunday) of the best overlapping slot found, if any.",
                        null=True,
                        verbose_name="best matching day",
                    ),
                ),
                (
                    "best_matching_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="best matching start time"
                    ),
                ),
                (
                    "best_matching_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="best matching end time"
                    ),
                ),
                (
                    "best_matching_timezone",
                    models.CharField(
                        blank=True,
                        help_text="Timezone the best_matching_* times are expressed in (the student's preference timezone).",
                        max_length=64,
                        null=True,
                        verbose_name="best matching timezone",
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("compatible", "Compatible"),
                            ("partially_compatible", "Partially Compatible"),
                            ("incompatible", "Incompatible"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="availability status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_score",
                        to="lead_engine.lead",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Match Score",
                "verbose_name_plural": "Lead Match Scores",
                "ordering": ["-match_score"],
                "indexes": [
                    models.Index(fields=["match_score"], name="idx_match_score"),
                    models.Index(
                        fields=["availability_status"], name="idx_availability_status"
                    ),
                ],
            },
        ),
    ]
