# Generated by Django 5.0.6 on 2026-09-01 07:58

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_engine", "0005_seed_lead_unlock_pricing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadunlockpricing",
            name="token_cost",
            field=models.PositiveIntegerField(
                help_text="Number of tokens required to unlock a lead in this tier.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100000),
                ],
                verbose_name="token cost",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadunlockpricing",
            constraint=models.CheckConstraint(
                check=models.Q(("token_cost__gte", 1), ("token_cost__lte", 100000)),
                name="lead_unlock_pricing_token_cost_range",
            ),
        ),
    ]
