# Generated by Django 5.0.14 on 2026-09-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_engine', '0006_alter_leadunlockpricing_token_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When this teacher rejected this lead, if they did.', null=True, verbose_name='rejected at'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=10, verbose_name='status'),
        ),
    ]
