# Generated by Django 5.0.6 on 2026-09-01 07:37

import apps.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Short language code, e.g. 'en', 'hi', 'es'. Recommended: ISO 639-1 two-letter codes for consistency, though not strictly enforced to allow regional variants if needed.",
                max_length=10,
                unique=True,
                validators=[apps.utils.validators.validate_language_code],
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Display name of the language, e.g. 'English'.",
                max_length=100,
                unique=True,
                validators=[apps.utils.validators.validate_taxonomy_name],
                verbose_name="name",
            ),
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("name__regex", "^\\s*$"), _negated=True),
                    models.Q(("code__regex", "^\\s*$"), _negated=True),
                ),
                name="language_name_and_code_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.CheckConstraint(
                check=models.Q(("code__regex", "^[a-z][a-z0-9-]{1,9}$")),
                name="language_code_format",
            ),
        ),
    ]
