# Generated by Django 5.0.14 on 2026-09-21 13:44

import apps.utils.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_code_alter_language_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='learning_partner',
            field=models.ForeignKey(blank=True, help_text="Null = platform-wide, visible to everyone. Set = a Learning Partner-requested language, visible only to that partner's own students/teachers.", limit_choices_to={'admin_department__is_learning_partner': True, 'role': 'admin'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoped_languages', to=settings.AUTH_USER_MODEL, verbose_name='learning partner'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(db_index=True, help_text="Short language code, e.g. 'en', 'hi', 'es'. Recommended: ISO 639-1 two-letter codes for consistency, though not strictly enforced to allow regional variants if needed.", max_length=10, validators=[apps.utils.validators.validate_language_code], verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(db_index=True, help_text="Display name of the language, e.g. 'English'.", max_length=100, validators=[apps.utils.validators.validate_taxonomy_name], verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(condition=models.Q(('learning_partner__isnull', True)), fields=('name',), name='language_name_unique_global'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(condition=models.Q(('learning_partner__isnull', True)), fields=('code',), name='language_code_unique_global'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('name', 'learning_partner'), name='language_name_unique_per_partner'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('code', 'learning_partner'), name='language_code_unique_per_partner'),
        ),
    ]
