# Generated by Django 5.0.14 on 2026-09-23 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0003_language_learning_partner_alter_language_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="learning_partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = platform-wide, visible to everyone. Set = a Learning Partner-requested language, visible only to that partner's own students/teachers.",
                limit_choices_to={"role": "learning_partner"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scoped_languages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="learning partner",
            ),
        ),
    ]
