# Generated by Django 5.0.6 on 2026-08-19 10:56

import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages", "0001_initial"),
        ("lead_engine", "0004_leadmatchscore"),
        ("subjects", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        help_text="Snapshot of the teacher's plan name at assignment time, e.g. 'Elite', 'Free'.",
                        max_length=50,
                        verbose_name="subscription tier",
                    ),
                ),
                (
                    "assignment_stage",
                    models.PositiveSmallIntegerField(
                        help_text="1 = first (highest-tier) group offered, 2 = next group after expiry/rejection, etc.",
                        verbose_name="assignment stage",
                    ),
                ),
                ("assigned_at", models.DateTimeField(verbose_name="assigned at")),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("viewed", "Viewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="assigned",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="viewed at"
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="responded at"
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        blank=True,
                        choices=[("accept", "Accept"), ("reject", "Reject")],
                        max_length=10,
                        null=True,
                        verbose_name="response",
                    ),
                ),
                (
                    "ranking_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="ranking score"
                    ),
                ),
                (
                    "time_match_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="time match score",
                    ),
                ),
                (
                    "location_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="location score",
                    ),
                ),
                (
                    "subject_match_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="subject match score",
                    ),
                ),
                (
                    "language_match_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="language match score",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="lead_engine.lead",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_assignments",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Assignment",
                "verbose_name_plural": "Lead Assignments",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchingConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "subject_match_threshold",
                    models.PositiveSmallIntegerField(
                        default=70,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="subject match threshold",
                    ),
                ),
                (
                    "language_match_threshold",
                    models.PositiveSmallIntegerField(
                        default=70,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="language match threshold",
                    ),
                ),
                (
                    "time_match_threshold_minutes",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Minimum overlap, in minutes, required for time-eligibility.",
                        verbose_name="time match threshold (minutes)",
                    ),
                ),
                (
                    "initial_location_radius_km",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="initial radius (km)"
                    ),
                ),
                (
                    "location_radius_increment_km",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="radius increment (km)"
                    ),
                ),
                (
                    "max_location_radius_km",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="max radius (km)"
                    ),
                ),
                (
                    "lead_response_window_hours",
                    models.PositiveSmallIntegerField(
                        default=24, verbose_name="lead response window (hours)"
                    ),
                ),
                (
                    "subscription_priority_order",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of plan names, highest priority first, e.g. ['Elite', 'Professional', 'Free'].",
                        verbose_name="subscription priority order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Matching Configuration",
                "verbose_name_plural": "Matching Configurations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PincodeLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "pincode",
                    models.CharField(
                        db_index=True,
                        max_length=10,
                        unique=True,
                        verbose_name="pincode",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        help_text="WGS84 latitude/longitude point for this pincode.",
                        srid=4326,
                        verbose_name="location",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="city"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="state"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="country"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pincode Location",
                "verbose_name_plural": "Pincode Locations",
                "ordering": ["pincode"],
            },
        ),
        migrations.CreateModel(
            name="SubjectAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "alias_text",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="alias text"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="subjects.subject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Alias",
                "verbose_name_plural": "Subject Aliases",
                "ordering": ["alias_text"],
            },
        ),
        migrations.CreateModel(
            name="LanguageAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "alias_text",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="alias text"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="languages.language",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Language Alias",
                "verbose_name_plural": "Language Aliases",
                "ordering": ["alias_text"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["alias_text"],
                        name="idx_language_alias_trgm",
                        opclasses=["gin_trgm_ops"],
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="languagealias",
            constraint=models.UniqueConstraint(
                fields=("language", "alias_text"), name="unique_language_alias"
            ),
        ),
        migrations.AddIndex(
            model_name="leadassignment",
            index=models.Index(
                fields=["status", "expires_at"], name="idx_assignment_expiry_scan"
            ),
        ),
        migrations.AddIndex(
            model_name="leadassignment",
            index=models.Index(
                fields=["lead", "assignment_stage"], name="idx_assignment_lead_stage"
            ),
        ),
        migrations.AddIndex(
            model_name="leadassignment",
            index=models.Index(
                fields=["teacher", "status"], name="idx_assignment_teacher_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="leadassignment",
            constraint=models.UniqueConstraint(
                fields=("lead", "teacher"), name="unique_assignment_per_lead_teacher"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectalias",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["alias_text"],
                name="idx_subject_alias_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectalias",
            constraint=models.UniqueConstraint(
                fields=("subject", "alias_text"), name="unique_subject_alias"
            ),
        ),
    ]
