# Generated by Django 5.0.6 on 2026-08-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pincodelocation",
            name="pincode",
            field=models.CharField(
                db_index=True, max_length=64, unique=True, verbose_name="pincode"
            ),
        ),
    ]
