# Generated by Django 5.0.6 on 2026-09-01 08:03

import django.core.validators
from django.conf import settings
from django.db import migrations, models

import apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0002_alter_language_code_alter_language_name_and_more"),
        ("matching", "0002_alter_pincodelocation_pincode"),
        ("subjects", "0002_alter_subject_description_alter_subject_icon_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="languagealias",
            name="alias_text",
            field=models.CharField(
                db_index=True,
                max_length=100,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="alias text",
            ),
        ),
        migrations.AlterField(
            model_name="matchingconfig",
            name="initial_location_radius_km",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5000),
                ],
                verbose_name="initial radius (km)",
            ),
        ),
        migrations.AlterField(
            model_name="matchingconfig",
            name="lead_response_window_hours",
            field=models.PositiveSmallIntegerField(
                default=24,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(720),
                ],
                verbose_name="lead response window (hours)",
            ),
        ),
        migrations.AlterField(
            model_name="matchingconfig",
            name="location_radius_increment_km",
            field=models.PositiveSmallIntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5000),
                ],
                verbose_name="radius increment (km)",
            ),
        ),
        migrations.AlterField(
            model_name="matchingconfig",
            name="max_location_radius_km",
            field=models.PositiveSmallIntegerField(
                default=20,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5000),
                ],
                verbose_name="max radius (km)",
            ),
        ),
        migrations.AlterField(
            model_name="matchingconfig",
            name="time_match_threshold_minutes",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Minimum overlap, in minutes, required for time-eligibility.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1440),
                ],
                verbose_name="time match threshold (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="pincodelocation",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[apps.utils.validators.validate_place_name],
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="pincodelocation",
            name="country",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[apps.utils.validators.validate_place_name],
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="pincodelocation",
            name="pincode",
            field=models.CharField(
                db_index=True,
                max_length=64,
                unique=True,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="pincode",
            ),
        ),
        migrations.AlterField(
            model_name="pincodelocation",
            name="state",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[apps.utils.validators.validate_place_name],
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="subjectalias",
            name="alias_text",
            field=models.CharField(
                db_index=True,
                max_length=150,
                validators=[apps.utils.validators.validate_no_control_characters],
                verbose_name="alias text",
            ),
        ),
        migrations.AddConstraint(
            model_name="languagealias",
            constraint=models.CheckConstraint(
                check=models.Q(("alias_text__regex", "^\\s*$"), _negated=True),
                name="language_alias_text_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchingconfig",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("subject_match_threshold__lte", 100),
                    ("language_match_threshold__lte", 100),
                    ("time_match_threshold_minutes__gte", 1),
                    ("time_match_threshold_minutes__lte", 1440),
                    ("initial_location_radius_km__gte", 1),
                    ("initial_location_radius_km__lte", 5000),
                    ("location_radius_increment_km__gte", 1),
                    ("location_radius_increment_km__lte", 5000),
                    ("max_location_radius_km__gte", 1),
                    ("max_location_radius_km__lte", 5000),
                    ("lead_response_window_hours__gte", 1),
                    ("lead_response_window_hours__lte", 720),
                    (
                        "initial_location_radius_km__lte",
                        models.F("max_location_radius_km"),
                    ),
                ),
                name="matching_config_sane_ranges",
            ),
        ),
        migrations.AddConstraint(
            model_name="pincodelocation",
            constraint=models.CheckConstraint(
                check=models.Q(("pincode__regex", "^\\s*$"), _negated=True),
                name="pincode_location_pincode_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectalias",
            constraint=models.CheckConstraint(
                check=models.Q(("alias_text__regex", "^\\s*$"), _negated=True),
                name="subject_alias_text_not_blank",
            ),
        ),
    ]
