# Generated by Django 5.0.6 on 2026-08-12 11:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when this record was created (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated (UTC).",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft-deleted, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("payment_success", "Payment Success"),
                            ("subscription_activated", "Subscription Activated"),
                            ("lead_unlocked", "Lead Unlocked"),
                            ("free_leads_exhausted", "Free Leads Exhausted"),
                            ("low_wallet_balance", "Low Wallet Balance"),
                            (
                                "subscription_expiry_reminder",
                                "Subscription Expiry Reminder",
                            ),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="event",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short notification headline, e.g. 'Payment Successful'.",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Full notification body text.", verbose_name="message"
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Id of the related object (Payment, Lead, TeacherSubscription, etc.), for the frontend to deep-link to. Not a foreign key since the reference type varies by event - same reasoning as WalletTransaction.reference_id.",
                        max_length=255,
                        null=True,
                        verbose_name="reference id",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the user has marked this in-app notification as read.",
                        verbose_name="is read",
                    ),
                ),
                (
                    "is_email_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether an email was successfully dispatched for this notification.",
                        verbose_name="email sent",
                    ),
                ),
                (
                    "email_error",
                    models.TextField(
                        blank=True,
                        help_text="Populated if email dispatch failed, for debugging.",
                        null=True,
                        verbose_name="email error",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this record, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(
                        fields=["user", "event"], name="notificatio_user_id_e2ced2_idx"
                    ),
                ],
            },
        ),
    ]
