# Generated by Django 5.0.14 on 2026-09-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('payment_success', 'Payment Success'), ('subscription_activated', 'Subscription Activated'), ('lead_unlocked', 'Lead Unlocked'), ('free_leads_exhausted', 'Free Leads Exhausted'), ('low_wallet_balance', 'Low Wallet Balance'), ('subscription_expiry_reminder', 'Subscription Expiry Reminder'), ('student_lead_unlocked', 'Teacher Unlocked Your Lead'), ('lead_review_pending', 'Lead Review Pending')], db_index=True, max_length=40, verbose_name='event'),
        ),
    ]
